"use client";
import {useMemo,useState} from "react";
export default function CalendarWorkspace({initial,brands,projects}:{initial:any[];brands:any[];projects:any[]}){
 const [events,setEvents]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(""),[brandId,setBrandId]=useState(brands[0]?.id||""),[projectId,setProjectId]=useState("");
 const [title,setTitle]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState("");
 const scopedProjects=projects.filter((p:any)=>!brandId||p.brand_id===brandId);
 const sorted=useMemo(()=>[...events].sort((a,b)=>new Date(a.start_at).getTime()-new Date(b.start_at).getTime()),[events]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC";const r=await fetch("/api/admin/calendar",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({brandId,projectId:projectId||null,title,startAt:new Date(start).toISOString(),endAt:new Date(end).toISOString(),timezone})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to create event");location.reload()}catch(e){setError(e instanceof Error?e.message:"Unable to create event")}finally{setBusy(false)}}
 async function status(id:string,next:string){setBusy(id);try{const r=await fetch("/api/admin/calendar/"+encodeURIComponent(id)+"/status",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({status:next})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to update event");setEvents(x=>x.map(e=>e.id===id?{...e,status:next}:e));}catch(e){setError(e instanceof Error?e.message:"Unable to update event")}finally{setBusy("")}}
 async function syncGoogle(id:string){setBusy(id);setError("");try{const r=await fetch("/api/admin/calendar/"+encodeURIComponent(id)+"/google",{method:"POST"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to sync event");setEvents(x=>x.map(e=>e.id===id?{...e,...j.event}:e));}catch(e){setError(e instanceof Error?e.message:"Unable to sync event")}finally{setBusy("")}}
 return <div className="calendarLayout"><section className="adminPanel"><div className="workspaceTitle"><div><p className="eyebrow">SCHEDULE</p><h2>One operating calendar</h2><p className="muted">Internal schedule authority now; Google Calendar sync activates after provider commissioning.</p></div></div><div className="todayList">{sorted.length===0?<p className="muted">No calendar events yet.</p>:sorted.map((e:any)=><div key={e.id}><time>{new Date(e.start_at).toLocaleDateString()}</time><strong>{e.title}</strong><small>{e.brand_name}{e.project_title?" · "+e.project_title:""} · {new Date(e.start_at).toLocaleString()} – {new Date(e.end_at).toLocaleTimeString()}</small><span>{e.status}{e.external_provider==="GOOGLE"?<small> · GOOGLE SYNCED</small>:e.status==="SCHEDULED"&&<button disabled={busy===e.id} onClick={()=>syncGoogle(e.id)}>Sync Google</button>}{e.status==="SCHEDULED"&&<><button disabled={busy===e.id} onClick={()=>status(e.id,"COMPLETE")}>Complete</button><button disabled={busy===e.id} onClick={()=>status(e.id,"CANCELLED")}>Cancel</button></>}</span></div>)}</div></section><section className="adminPanel"><p className="eyebrow">NEW EVENT</p><h2>Add to schedule</h2><form onSubmit={create} style={{display:"grid",gap:12}}><label>Brand<select value={brandId} onChange={e=>{setBrandId(e.target.value);setProjectId("")}} required>{brands.map((b:any)=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label><label>Project <select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">No project</option>{scopedProjects.map((p:any)=><option value={p.id} key={p.id}>{p.title}</option>)}</select></label><label>Event<input value={title} onChange={e=>setTitle(e.target.value)} required placeholder="Call, rehearsal, service, deadline…"/></label><label>Starts<input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)} required/></label><label>Ends<input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)} required/></label>{error&&<p role="alert">{error}</p>}<button disabled={busy}>{busy?"Saving…":"Add Event →"}</button></form></section></div>
}