"use client";
import {useState} from "react";import {useRouter} from "next/navigation";
export default function CommercialForms({brands,organizations,contacts,opportunities}:{brands:any[];organizations:any[];contacts:any[];opportunities:any[]}){
 const router=useRouter();const [mode,setMode]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const [org,setOrg]=useState({name:"",type:"CLIENT",website:"",brandId:brands[0]?.id||""});
 const [contact,setContact]=useState({firstName:"",lastName:"",email:"",phone:"",role:"",organizationId:"",brandId:brands[0]?.id||""});
 const [opp,setOpp]=useState({title:"",brandId:brands[0]?.id||"",value:"",organizationId:"",primaryContactId:""});
 async function send(url:string,body:any,method:string="POST"){setBusy(true);setError("");const r=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||"Unable to save");return false}setMode("");router.refresh();return true}
 async function stage(id:string,stage:string){await send("/api/admin/opportunities/"+id+"/stage",{stage},"PUT" as any)}
 async function proposal(id:string){await send("/api/admin/proposals",{opportunityId:id})}
 return <section className="adminPanel" style={{marginTop:18}}><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><button onClick={()=>setMode("opportunity")}>+ Opportunity</button><button onClick={()=>setMode("contact")}>+ Contact</button><button onClick={()=>setMode("organization")}>+ Organization</button></div>
 {error&&<p className="muted">{error}</p>}
 {mode==="organization"&&<div style={{display:"grid",gap:10,marginTop:14}}><h2>New Organization</h2><label>Name<input value={org.name} onChange={e=>setOrg({...org,name:e.target.value})}/></label><label>Type<input value={org.type} onChange={e=>setOrg({...org,type:e.target.value})}/></label><label>Website<input value={org.website} onChange={e=>setOrg({...org,website:e.target.value})}/></label><label>Brand<select value={org.brandId} onChange={e=>setOrg({...org,brandId:e.target.value})}>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button className="primary" disabled={busy||!org.name} onClick={()=>send("/api/admin/organizations",{...org,brandIds:[org.brandId]})}>Create Organization →</button></div>}
 {mode==="contact"&&<div style={{display:"grid",gap:10,marginTop:14}}><h2>New Contact</h2><label>First name<input value={contact.firstName} onChange={e=>setContact({...contact,firstName:e.target.value})}/></label><label>Last name<input value={contact.lastName} onChange={e=>setContact({...contact,lastName:e.target.value})}/></label><label>Email<input type="email" value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})}/></label><label>Phone<input value={contact.phone} onChange={e=>setContact({...contact,phone:e.target.value})}/></label><label>Role<input value={contact.role} onChange={e=>setContact({...contact,role:e.target.value})}/></label><label>Organization<select value={contact.organizationId} onChange={e=>setContact({...contact,organizationId:e.target.value})}><option value="">None</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Brand<select value={contact.brandId} onChange={e=>setContact({...contact,brandId:e.target.value})}>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button className="primary" disabled={busy||!contact.firstName||!contact.lastName} onClick={()=>send("/api/admin/contacts",{...contact,brandIds:[contact.brandId]})}>Create Contact →</button></div>}
 {mode==="opportunity"&&<div style={{display:"grid",gap:10,marginTop:14}}><h2>New Opportunity</h2><label>Title<input value={opp.title} onChange={e=>setOpp({...opp,title:e.target.value})}/></label><label>Brand<select value={opp.brandId} onChange={e=>setOpp({...opp,brandId:e.target.value})}>{brands.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Estimated value ($)<input inputMode="decimal" value={opp.value} onChange={e=>setOpp({...opp,value:e.target.value})}/></label><label>Organization<select value={opp.organizationId} onChange={e=>setOpp({...opp,organizationId:e.target.value})}><option value="">None</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Primary contact<select value={opp.primaryContactId} onChange={e=>setOpp({...opp,primaryContactId:e.target.value})}><option value="">None</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.first_name} {c.last_name}</option>)}</select></label><button className="primary" disabled={busy||!opp.title} onClick={()=>send("/api/admin/opportunities",{brandId:opp.brandId,title:opp.title,valueCents:Math.round(Number(opp.value||0)*100),organizationId:opp.organizationId||null,primaryContactId:opp.primaryContactId||null})}>Create Opportunity →</button></div>}
 {opportunities.length>0&&<div style={{display:"grid",gap:10,marginTop:20}}><h2>Pipeline Actions</h2>{opportunities.map(o=><div key={o.id} style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><strong style={{minWidth:180}}>{o.title}</strong><span>{o.stage}</span><select value={o.stage} onChange={e=>stage(o.id,e.target.value)}><option>NEW</option><option>QUALIFYING</option><option>DISCOVERY</option><option>PROPOSAL</option><option>NEGOTIATION</option><option>WON</option><option>LOST</option></select>{!o.proposal_id&&<button disabled={busy} onClick={()=>proposal(o.id)}>Create Proposal</button>}</div>)}</div>}
 </section>
}