"use client";
import {useState} from "react";import {useRouter} from "next/navigation";
const short:{[k:string]:string}={bassOne:"B1",cgSuccess:"CG",charminJermaine:"C&J",charmin:"CG",dionnesBoutique:"DB",jermaine:"JW",soundLegacy:"SLI",studio2016:"S16"};
export default function ContractingReadiness({rows}:{rows:any[]}){
 const router=useRouter();const [busy,setBusy]=useState("");const [message,setMessage]=useState("");
 async function approve(r:any){setBusy(r.id);setMessage("");try{const res=await fetch("/api/admin/agreement-terms/"+r.terms_id,{method:"PUT",headers:{"content-type":"application/json"},body:"{}"});const j=await res.json();if(!res.ok)throw new Error(j.error||"Unable to approve terms");router.refresh()}catch(e){setMessage(e instanceof Error?e.message:"Unable to approve terms")}finally{setBusy("")}}
 const legal=(r:any)=>Boolean(r.complete_for_signing)&&Number(r.verified_signers||0)>0&&Number(r.active_entities||0)>0;
 const ready=rows.filter(legal).length,drafts=rows.filter(r=>r.terms_status==="DRAFT").length,missing=rows.filter(r=>!r.terms_status).length,payments=rows.filter(r=>r.complete_for_payment).length;
 return <section className="readinessWorkspace"><div className="readinessHero"><div><p className="eyebrow">CONTRACTS & PAYMENTS</p><h2>Contracting Readiness</h2><p>See exactly what is ready, what needs review, and what must happen next for every brand.</p></div></div>
 <div className="readinessMetrics"><article className="metricReady"><strong>{ready}</strong><span>CONTRACTING READY</span><small>Identity & signer configured</small></article><article className="metricDraft"><strong>{drafts}</strong><span>TERMS IN REVIEW</span><small>Draft master terms</small></article><article className="metricMissing"><strong>{missing}</strong><span>TERMS MISSING</span><small>Master terms not created</small></article><article><strong>{payments}</strong><span>PAYMENTS ACTIVE</span><small>Provider commissioned</small></article></div>
 {message&&<p className="systemMessage">{message}</p>}
 <div className="readinessTable"><div className="readinessHead"><span>BRAND</span><span>CONTRACTING</span><span>LEGAL TERMS</span><span>PAYMENTS</span><span>NEXT STEP</span><span/></div>{rows.map(r=>{const l=legal(r),terms=r.terms_status||"NOT CONFIGURED",pay=r.complete_for_payment?"READY":(r.payment_mode||"NOT CONFIGURED");return <article className="readinessRow" key={r.id}><div className="brandIdentity"><i>{short[r.id]||r.name.slice(0,2)}</i><div><strong>{r.name}</strong><small>{r.contracting_name&&r.contracting_name!==r.name?r.contracting_name:"Brand account"}</small></div></div><div><span className={"statePill "+(l?"ready":"missing")}>{l?"✓ READY":"! INCOMPLETE"}</span><small>{l?"Configured":"Needs setup"}</small></div><div><span className={"statePill "+(terms==="APPROVED"?"ready":terms==="DRAFT"?"draft":"missing")}>{terms==="DRAFT"?"◷ ":terms==="APPROVED"?"✓ ":"! "}{terms}</span><small>{terms==="DRAFT"?"Needs review":terms==="APPROVED"?"Approved":"No terms created"}</small></div><div><span className={"statePill "+(r.complete_for_payment?"ready":"neutral")}>{pay}</span><small>{r.complete_for_payment?"Enabled":pay==="EXTERNAL"?"Outside WGOS":"Not enabled"}</small></div><div className="nextStep"><b className={terms==="DRAFT"?"dotDraft":"dotMissing"}/><span>{terms==="DRAFT"?"Review & approve master terms":terms==="APPROVED"?(r.complete_for_payment?"Ready for transactions":"Commission payments"):"Create master terms"}</span></div><div>{terms==="DRAFT"?<button className="goldAction" disabled={busy===r.id||!l} onClick={()=>approve(r)}>{busy===r.id?"Working…":"Review →"}</button>:<span className="quietAction">{terms==="APPROVED"?"READY":"SET UP"}</span>}</div></article>})}</div></section>;
}