import Link from "next/link";
export default function ExecutiveAttention({proposals,readiness,agreements,projects,threads=[]}:{proposals:any[];readiness:any[];agreements:any[];projects:any[];threads?:any[]}){
 const drafts=proposals.filter(p=>p.status==="DRAFT").length,clientWaiting=threads.filter(t=>t.recent_direction==="INBOUND").length,awaitingClient=proposals.filter(p=>["APPROVED","SENT"].includes(p.status)).length,accepted=proposals.filter(p=>p.status==="ACCEPTED").length,signature=agreements.filter(a=>a.status==="READY_FOR_SIGNATURE").length,setup=readiness.filter(r=>!r.complete_for_signing||r.terms_status!=="APPROVED"||!r.complete_for_payment).length,blocked=projects.filter(p=>p.status==="BLOCKED").length,active=projects.filter(p=>["PLANNING","ACTIVE","BLOCKED"].includes(p.status)).length;
 const decisions=[
  {priority:"NOW",label:"Client responses",count:clientWaiting,note:"Clients have spoken. Review and respond.",href:"/admin/communications",human:true},
  {priority:"DECIDE",label:"Accepted proposals",count:accepted,note:"Authorize the agreement step.",href:"#contracting",human:true},
  {priority:"DECIDE",label:"Signature queue",count:signature,note:"Review provider/signature movement.",href:"#contracting",human:true},
  {priority:"RISK",label:"Blocked delivery",count:blocked,note:"Intervention may be required.",href:"/admin/operations",human:true},
  {priority:"SETUP",label:"Brand readiness",count:setup,note:"Finish contract or payment commissioning.",href:"#contracting",human:true},
 ].filter(x=>x.count>0);
 const routine=drafts+awaitingClient+Math.max(0,active-blocked);
 const items=[["Proposal drafts",drafts,"Prepare or approve","#commercial-forms"],["Client waiting",clientWaiting,"Respond","/admin/communications"],["Awaiting client",awaitingClient,"Proposal response","#commercial-forms"],["Accepted",accepted,"Advance agreement","#contracting"],["Signature queue",signature,"Provider action","#contracting"],["Setup attention",setup,"Contract/payment readiness","#contracting"],["Active delivery",active,"Operations","/admin/operations"]];
 return <><section className="adminPanel decisionQueue" aria-label="Decision queue"><div className="attentionIntro"><p className="eyebrow">WGOS AUTOPILOT · DECISION QUEUE</p><h2>{decisions.length?decisions.length+" decision"+(decisions.length===1?"":"s")+" need you":"Nothing requires intervention"}</h2><p>{decisions.length?"Routine work stays in its lanes. Your attention is reserved for judgment, approvals and exceptions.":"WGOS sees no current exception requiring executive judgment."}</p></div><div className="decisionList">{decisions.slice(0,5).map(x=><Link href={x.href} key={x.label} className="decisionItem"><span>{x.priority}</span><strong>{x.count} · {x.label}</strong><small>{x.note}</small><b>Open →</b></Link>)}</div><div className="autopilotFooter"><strong>{routine}</strong><span>routine item{routine===1?"":"s"} monitored outside the decision queue</span></div></section><section className="attentionStrip" aria-label="Executive attention"><div className="attentionIntro"><p className="eyebrow">OPERATING SIGNALS</p><h2>What is moving</h2></div><div className="attentionItems">{items.map(([label,count,note,href])=><Link href={String(href)} className={Number(count)>0?"attentionItem active":"attentionItem"} key={String(label)}><strong>{count}</strong><span>{label}</span><small>{note} →</small></Link>)}</div></section></>;
}