"use client";
import {useState} from "react";

export default function GoogleCommissioning({initial=[]}:{initial:any[]}){
 const seed=Object.fromEntries(["gmail","calendar","drive"].map(cap=>{const r=initial.find((x:any)=>String(x.provider).toLowerCase()==="google"&&String(x.capability).toLowerCase()===cap);return [cap,{status:r?.status||"UNVERIFIED",busy:false,error:r?.last_error||"",metadata:r?.metadata||{}}]}));
 const [state,setState]=useState<any>(seed);
 async function verify(capability:"gmail"|"calendar"|"drive"){setState((s:any)=>({...s,[capability]:{...(s[capability]||{}),busy:true,error:""}}));try{const r=await fetch("/api/admin/integrations/google/verify?capability="+capability,{cache:"no-store"});const j=await r.json();setState((s:any)=>({...s,[capability]:{status:j.connected?"CONNECTED":"ERROR",busy:false,error:j.connected?"":j.error||"Not verified",metadata:j}}));}catch{setState((s:any)=>({...s,[capability]:{...(s[capability]||{}),status:"ERROR",busy:false,error:"Unable to verify"}}));}}
 const rows=[["gmail","Gmail","Client communication transport"],["calendar","Google Calendar","External schedule authority"],["drive","Google Drive","Document storage authority"]] as const;
 return <section className="adminPanel"><div className="integrationHead"><div><p className="eyebrow">GOOGLE WORKSPACE COMMISSIONING</p><h2>Communication, Calendar & Drive</h2><p className="muted">WGOS keeps canonical business context while Google remains the external transport/storage provider.</p></div></div><div className="todayList">{rows.map(([id,label,note])=>{const x=state[id]||{};return <div key={id}><time>{x.status==="CONNECTED"?"CONNECTED":"VERIFY"}</time><strong>{label}</strong><small>{x.status==="CONNECTED"?(x.metadata?.account||x.metadata?.calendarId||"Provider verified"):x.error||note}</small><button className="journeyLinkButton" disabled={x.busy} onClick={()=>verify(id)}>{x.busy?"Checking…":"Verify "+label}</button></div>})}</div></section>
}