"use client";
import {useState} from "react";
export default function IntegrationStatus({initial=[]}:{initial?:any[]}){
 const map=Object.fromEntries(initial.map((x:any)=>[String(x.provider).toLowerCase(),x]));
 const [state,setState]=useState<any>({
  signwell:map.signwell?.status==="CONNECTED"?"connected":map.signwell?.status==="ERROR"?"attention":"unchecked",
  stripe:map.stripe?.status==="CONNECTED"?"connected":map.stripe?.status==="ERROR"?"attention":"unchecked",
  signwellDetail:map.signwell?.status==="CONNECTED"?"Verified":map.signwell?.last_error||"",
  stripeDetail:map.stripe?.status==="CONNECTED"?"Verified":map.stripe?.last_error||"",
  signwellMode:map.signwell?.metadata?.mode||"",
  signwellWebhook:Boolean(map.signwell?.metadata?.webhookConfigured),
  stripeMode:map.stripe?.metadata?.mode||""
 });
 async function registerWebhook(){setState((x:any)=>({...x,signwellDetail:"Registering webhook…"}));try{const r=await fetch("/api/admin/integrations/signwell/webhook",{method:"POST"});const j=await r.json();setState((x:any)=>({...x,signwellWebhook:Boolean(r.ok&&j.configured),signwellDetail:r.ok?"Webhook registered":j.error||"Webhook registration failed",signwellMode:j.mode||x.signwellMode}));}catch{setState((x:any)=>({...x,signwellDetail:"Webhook registration failed"}));}}
 async function check(provider:"signwell"|"stripe"){setState((s:any)=>({...s,[provider]:"checking",[provider+"Detail"]:""}));try{const r=await fetch(`/api/admin/integrations/${provider}/verify`,{cache:"no-store"});const j=await r.json();setState((s:any)=>({...s,[provider]:j.connected?"connected":"attention",[provider+"Detail"]:j.connected?"Verified":"Not verified",[provider+"Mode"]:j.mode||s[provider+"Mode"]||"",...(provider==="signwell"?{signwellWebhook:Boolean(j.webhookConfigured)}:{})}));}catch{setState((s:any)=>({...s,[provider]:"attention",[provider+"Detail"]:"Unable to verify"}));}}
 const label=(provider:"signwell"|"stripe")=>state[provider]==="connected"?`CONNECTED${state[provider+"Mode"]?" · "+state[provider+"Mode"]:""}`:state[provider]==="checking"?"CHECKING…":state[provider+"Detail"]||"NOT VERIFIED";
 return <section className="adminPanel integrationPanel"><div className="integrationHead"><div><p className="eyebrow">PROVIDER COMMISSIONING</p><h2>Integration Health</h2><p className="muted">External providers remain authoritative for signatures and payments. Successful live checks are persisted in WGOS.</p></div><div className="providerLegend"><span>● LIVE CHECK</span><small>Verify against provider</small></div></div><div className="integrationRow"><div><strong>SignWell</strong><small>Electronic signature provider · TEST is non-binding; LIVE is client-ready · webhook {state.signwellWebhook?"registered":"not verified"}</small></div><span className={"status "+state.signwell}>{label("signwell")}</span><span className="integrationActions"><button onClick={()=>check("signwell")} disabled={state.signwell==="checking"}>Verify Connection</button>{state.signwell==="connected"&&!state.signwellWebhook&&<button onClick={registerWebhook}>Register Webhook</button>}</span></div><div className="integrationRow"><div><strong>Stripe</strong><small>Hosted checkout, payment confirmations and receipts</small></div><span className={"status "+state.stripe}>{label("stripe")}</span><button onClick={()=>check("stripe")} disabled={state.stripe==="checking"}>Verify Connection</button></div></section>;
}