"use client";
import {useEffect,useMemo,useState} from "react";
const stages=["NEW","QUALIFYING","DISCOVERY","PROPOSAL","NEGOTIATION","WON","LOST"];
const nextAction=(stage:string,hasProposal:boolean)=>stage==="NEW"?"Qualify lead":stage==="QUALIFYING"?"Start discovery":stage==="DISCOVERY"?"Build proposal":stage==="PROPOSAL"?(hasProposal?"Review proposal":"Create proposal"):stage==="NEGOTIATION"?"Close terms":stage==="WON"?"Activate delivery":stage==="LOST"?"Archive":"Review";
export default function OpportunityWorkspace({opportunities,proposals,initialOpportunityId=""}:{opportunities:any[];proposals:any[];initialOpportunityId?:string}){
 const [filter,setFilter]=useState("ALL");const [selected,setSelected]=useState(initialOpportunityId);useEffect(()=>{const h=(e:any)=>setFilter(e.detail||"ALL");window.addEventListener("wgos:brand-filter",h);return()=>window.removeEventListener("wgos:brand-filter",h)},[]);
 const rows=useMemo(()=>opportunities.filter(o=>filter==="ALL"||o.brand_id===filter),[opportunities,filter]);
 const proposalByOpp=useMemo(()=>new Map(proposals.map(p=>[p.opportunity_id,p])),[proposals]);const openRows=rows.filter(o=>!["WON","LOST"].includes(o.stage));const unassigned=openRows.filter(o=>!o.owner_name).length;const proposalStage=openRows.filter(o=>["PROPOSAL","NEGOTIATION"].includes(o.stage)).length;
 return <section className="adminPanel opportunityWorkspace"><div className="workspaceTitle"><div><p className="eyebrow">REVENUE PIPELINE</p><h2>Opportunities</h2><p className="muted">A single view from first conversation through proposal, agreement, payment and delivery.</p></div><div className="pipelineSignals"><span><b>{openRows.length}</b> OPEN</span><span><b>{proposalStage}</b> PROPOSAL / TERMS</span><span className={unassigned?"warn":""}><b>{unassigned}</b> UNASSIGNED</span></div><div className="pipelineTotal"><small>OPEN VALUE</small><strong>{"$"+rows.filter(o=>!["WON","LOST"].includes(o.stage)).reduce((n,o)=>n+Number(o.estimated_value||0),0).toLocaleString()}</strong></div></div>
 {rows.length===0?<div className="emptyAttention"><h2>No opportunities in this view.</h2><p>Create an opportunity or select another brand.</p></div>:<div className="opportunityList">{rows.map(o=>{const p:any=proposalByOpp.get(o.id);const idx=Math.max(0,stages.indexOf(o.stage));return <article id={"opportunity-"+o.id} className={"opportunityCard "+(selected===o.id?"selectedRecord":"")} key={o.id} onClick={()=>setSelected(selected===o.id?"":o.id)}><div className="oppTop"><div><span className="status">{o.stage}</span><h3>{o.title}</h3><p>{o.organization_name||"Direct client"}{o.first_name?" · "+o.first_name+" "+o.last_name:""} · {o.brand_name}</p></div><strong className="oppValue">{"$"+Number(o.estimated_value||0).toLocaleString()}</strong></div><div className="stageRail" aria-label={"Stage "+o.stage}>{stages.slice(0,6).map((s,i)=><span key={s} className={i<=idx&&o.stage!=="LOST"?"done":""} title={s}/>)}</div><div className="oppFoot"><span>Proposal: <b>{p?p.status:"NOT CREATED"}</b></span><span>{p?"v"+p.version:"Ready for qualification"}</span><span>{o.owner_name?"Owner: "+o.owner_name:"Unassigned"}</span></div></article>})}</div>}
 </section>;
}