"use client";
import {useEffect,useMemo,useState} from "react";
const stages=["NEW","QUALIFYING","DISCOVERY","PROPOSAL","NEGOTIATION","WON","LOST"];
const nextAction=(stage:string,hasProposal:boolean,discovery?:any)=>discovery?.status==="READY_FOR_PROPOSAL"&&!hasProposal?"Build proposal":stage==="NEW"?"Qualify lead":stage==="QUALIFYING"?"Continue discovery":stage==="DISCOVERY"?"Complete discovery":stage==="PROPOSAL"?(hasProposal?"Review proposal":"Create proposal"):stage==="NEGOTIATION"?"Close terms":stage==="WON"?"Activate delivery":stage==="LOST"?"Archive":"Review";
export default function OpportunityWorkspace({opportunities,proposals,initialOpportunityId=""}:{opportunities:any[];proposals:any[];initialOpportunityId?:string}){
 const [filter,setFilter]=useState("ALL");const [selected,setSelected]=useState(initialOpportunityId);const [busy,setBusy]=useState("");const [message,setMessage]=useState("");useEffect(()=>{const h=(e:any)=>setFilter(e.detail||"ALL");window.addEventListener("wgos:brand-filter",h);return()=>window.removeEventListener("wgos:brand-filter",h)},[]);useEffect(()=>{if(!selected)return;const el=document.getElementById("opportunity-"+selected);if(el){const reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;requestAnimationFrame(()=>el.scrollIntoView({behavior:reduced?"auto":"smooth",block:"center"}));}},[selected]);
 async function createProposal(opportunityId:string){
  setBusy(opportunityId);setMessage("");
  try{
   const r=await fetch("/api/admin/proposals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({opportunityId})});
   const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to create proposal");
   setMessage("Proposal draft created. Review scope, pricing, assumptions and approval controls before client release.");
   window.location.reload();
  }catch(e){setMessage(e instanceof Error?e.message:"Unable to create proposal");}
  finally{setBusy("");}
 }
 function scrollTo(id:string){document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"});}
 const rows=useMemo(()=>opportunities.filter(o=>filter==="ALL"||o.brand_id===filter),[opportunities,filter]);
 const proposalByOpp=useMemo(()=>new Map(proposals.map(p=>[p.opportunity_id,p])),[proposals]);const openRows=rows.filter(o=>!["WON","LOST"].includes(o.stage));const unassigned=openRows.filter(o=>!o.owner_name).length;const proposalStage=openRows.filter(o=>["PROPOSAL","NEGOTIATION"].includes(o.stage)).length;const daysSince=(v:any)=>Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/86400000));const ageDays=(o:any)=>daysSince(o.updated_at||o.created_at);const salesQueue=openRows.map((o:any)=>{const p:any=proposalByOpp.get(o.id);let days=ageDays(o);if(p&&["APPROVED","SENT"].includes(p.status))days=daysSince(p.sent_at||p.approved_at||p.updated_at||p.created_at);let reason="",priority=0;if(!o.owner_name){reason="Needs an owner";priority=90}else if(o.stage==="NEW"&&days>=1){reason="Qualify this lead";priority=80+Math.min(days,9)}else if(o.stage==="QUALIFYING"&&days>=2){reason="Move into discovery";priority=70+Math.min(days,9)}else if(o.stage==="DISCOVERY"&&days>=3){reason="Build the recommendation";priority=70+Math.min(days,9)}else if(o.stage==="PROPOSAL"&&!p){reason="Proposal has not been created";priority=85}else if(p&&["APPROVED","SENT"].includes(p.status)&&days>=3){reason="Proposal needs follow-up";priority=75+Math.min(days,9)}else if(o.stage==="NEGOTIATION"&&days>=2){reason="Terms need movement";priority=82+Math.min(days,9)}return {...o,_proposal:p,_days:days,_reason:reason,_priority:priority}}).filter((o:any)=>o._reason).sort((a:any,b:any)=>b._priority-a._priority);
 return <>{message&&<p className="lifecycleMessage" role="status">{message}</p>}<section className="adminPanel salesAutopilot"><div className="attentionIntro"><p className="eyebrow">SALES AUTOPILOT · NEXT MOVES</p><h2>{salesQueue.length?salesQueue.length+" commercial move"+(salesQueue.length===1?"":"s")+" need attention":"Pipeline is moving cleanly"}</h2><p>{salesQueue.length?"WGOS is ranking open revenue by ownership gaps, stage friction and time without movement.":"No open opportunity currently crosses the attention thresholds."}</p></div><div className="salesDecisionList">{salesQueue.slice(0,6).map((o:any)=><button key={"sales-"+o.id} className="salesDecisionItem" onClick={()=>{setSelected(o.id);requestAnimationFrame(()=>document.getElementById("opportunity-"+o.id)?.scrollIntoView({behavior:"smooth",block:"center"}))}}><span>{o.brand_name} · {o.stage}</span><strong>{o.title}</strong><small>{o._reason} · {o._days}d since movement</small><b>{"$"+Number(o.estimated_value||0).toLocaleString()} →</b></button>)}</div></section><section className="adminPanel opportunityWorkspace"><div className="workspaceTitle"><div><p className="eyebrow">REVENUE PIPELINE</p><h2>Opportunities</h2><p className="muted">A single view from first conversation through proposal, agreement, payment and delivery.</p></div><div className="pipelineSignals"><span><b>{openRows.length}</b> OPEN</span><span><b>{proposalStage}</b> PROPOSAL / TERMS</span><span className={unassigned?"warn":""}><b>{unassigned}</b> UNASSIGNED</span></div><div className="pipelineTotal"><small>OPEN VALUE</small><strong>{"$"+rows.filter(o=>!["WON","LOST"].includes(o.stage)).reduce((n,o)=>n+Number(o.estimated_value||0),0).toLocaleString()}</strong></div></div>
 {rows.length===0?<div className="emptyAttention"><h2>No opportunities in this view.</h2><p>Create an opportunity or select another brand.</p></div>:<div className="opportunityList">{rows.map(o=>{const p:any=proposalByOpp.get(o.id);const idx=Math.max(0,stages.indexOf(o.stage));return <article id={"opportunity-"+o.id} className={"opportunityCard "+(selected===o.id?"selectedRecord":"")} key={o.id} onClick={()=>setSelected(selected===o.id?"":o.id)}><div className="oppTop"><div><span className="status">{o.stage}</span><h3>{o.title}</h3><p>{o.organization_name||"Direct client"}{o.first_name?" · "+o.first_name+" "+o.last_name:""} · {o.brand_name}</p></div><strong className="oppValue">{"$"+Number(o.estimated_value||0).toLocaleString()}</strong></div><div className="stageRail" aria-label={"Stage "+o.stage}>{stages.slice(0,6).map((s,i)=><span key={s} className={i<=idx&&o.stage!=="LOST"?"done":""} title={s}/>)}</div><div className="oppFoot"><span>Proposal: <b>{p?p.status:"NOT CREATED"}</b></span><span>{p?"v"+p.version:(o.discovery?._discovery?.status==="READY_FOR_PROPOSAL"?"Discovery ready":o.discovery?._discovery?.readiness!=null?"Discovery "+o.discovery._discovery.readiness+"%":"Ready for qualification")}</span><span>{o.owner_name?"Owner: "+o.owner_name:"Unassigned"}</span></div>{selected===o.id&&<div className="recordContext"><div><small>NEXT MOVE</small><strong>{nextAction(o.stage,Boolean(p),o.discovery?._discovery)}</strong></div><div><small>RELATIONSHIP</small><strong>{o.organization_name||((o.first_name||o.last_name)?[o.first_name,o.last_name].filter(Boolean).join(" "):"Direct client")}</strong></div><div><small>COMMERCIAL STATE</small><strong>{p?"Proposal "+p.status:o.stage}</strong></div>{o.discovery?._discovery&&<div><small>DISCOVERY</small><strong>{o.discovery._discovery.readiness??0}% · {String(o.discovery._discovery.status||"DISCOVERY_REQUIRED").replaceAll("_"," ")}</strong><span className="contextHint">{Array.isArray(o.discovery._discovery.missing)&&o.discovery._discovery.missing.length?"Still needed: "+o.discovery._discovery.missing.slice(0,3).join(", "):"Core discovery is complete."}</span></div>}{!p&&o.discovery?._discovery?.status==="READY_FOR_PROPOSAL"
 ?<button className="lifecycleButton" disabled={busy===o.id} onClick={e=>{e.stopPropagation();createProposal(o.id)}}>{busy===o.id?"Creating…":"Create Proposal Draft →"}</button>
 :p?.status==="DRAFT"
  ?<button className="lifecycleButton" onClick={e=>{e.stopPropagation();scrollTo("commercial-forms")}}>Review Proposal →</button>
  :p&&["APPROVED","SENT","ACCEPTED"].includes(p.status)
   ?<button className="lifecycleButton" onClick={e=>{e.stopPropagation();scrollTo("commercial-lifecycle")}}>Open Next Commercial Step →</button>
   :<button className="lifecycleButton" onClick={e=>{e.stopPropagation();scrollTo("commercial-forms")}}>Open Action Center →</button>}
</div>}</article>})}</div>}
 </section></>;
}