import Link from "next/link";
import {commercialSummary,listOpportunities} from "../../lib/commercial";
import {listProposals,clientExperienceReadiness} from "../../lib/documents";
import {commercialReadiness,commercialLifecycleRecords} from "../../lib/commercial-lifecycle";
import {relationshipReferenceData} from "../../lib/relationships";
import CommercialForms from "./CommercialForms";
import AdminNav from "./AdminNav";
import RelationshipWorkspace from "./RelationshipWorkspace";
import OpportunityWorkspace from "./OpportunityWorkspace";
import LifecycleWorkspace from "./LifecycleWorkspace";
import ExecutiveAttention from "./ExecutiveAttention";
import IntegrationStatus from "./IntegrationStatus";
import ContractingReadiness from "./ContractingReadiness";
import ClientExperienceReadiness from "./ClientExperienceReadiness";
export default async function AdminPage({searchParams}:{searchParams:Promise<{brand?:string;contact?:string;organization?:string;opportunity?:string;proposal?:string}>}){
 const query=await searchParams;const selectedBrand=query.brand||"";
 let opportunities:any[]=[],proposals:any[]=[],readiness:any[]=[],experienceReadiness:any[]=[],lifecycle:any={agreements:[],payments:[],projects:[]},refs:any={brands:[],organizations:[],contacts:[]};
 try{[opportunities,refs,proposals,readiness,experienceReadiness,lifecycle]=await Promise.all([listOpportunities(),relationshipReferenceData(),listProposals(),commercialReadiness(),clientExperienceReadiness(),commercialLifecycleRecords()]);}catch{}
 if(selectedBrand){opportunities=opportunities.filter((o:any)=>o.brand_id===selectedBrand);proposals=proposals.filter((p:any)=>p.brand_id===selectedBrand);readiness=readiness.filter((r:any)=>r.id===selectedBrand);experienceReadiness=experienceReadiness.filter((r:any)=>r.id===selectedBrand);lifecycle={agreements:lifecycle.agreements.filter((x:any)=>x.brand_id===selectedBrand),payments:lifecycle.payments.filter((x:any)=>x.brand_id===selectedBrand),projects:lifecycle.projects.filter((x:any)=>x.brand_id===selectedBrand)};refs={...refs,organizations:refs.organizations.filter((x:any)=>(x.brand_ids||[]).includes(selectedBrand)),contacts:refs.contacts.filter((x:any)=>(x.brand_ids||[]).includes(selectedBrand))};}
 const open=opportunities.filter((o:any)=>!["WON","LOST"].includes(o.stage));const clientResponseThreads=(refs.threadLinks||[]).filter((t:any)=>t.recent_direction==="INBOUND");const pipelineValue=open.reduce((n:number,o:any)=>n+Number(o.estimated_value||0),0);const activeProjects=lifecycle.projects.filter((p:any)=>["PLANNING","ACTIVE","BLOCKED"].includes(p.status));const blocked=activeProjects.filter((p:any)=>p.status==="BLOCKED").length;const waiting=clientResponseThreads.length;const proposalWaiting=proposals.filter((p:any)=>["APPROVED","SENT"].includes(p.status)).length;const readyBrands=readiness.filter((r:any)=>r.complete_for_signing&&r.terms_status==="APPROVED"&&r.complete_for_payment).length;
 return <main className="admin"><AdminNav active="commercial" brands={refs.brands} brand={selectedBrand}/>
 <header className="adminHead commandHero"><div><p className="eyebrow">WGOS · EXECUTIVE PULSE</p><h1>{selectedBrand?"Brand Command":"Command Center"}</h1><p>{selectedBrand?"Focused operating view for the selected brand.":"One governed view of commercial movement, delivery and decisions across the portfolio."}</p></div><div className="adminActions"><Link href="/admin/operations">Open Operations →</Link></div></header>
 <section className="pulseGrid" aria-label="Business pulse"><article><small>OPEN PIPELINE</small><strong>{"$"+pipelineValue.toLocaleString(undefined,{maximumFractionDigits:0})}</strong><span>{open.length} live opportunities</span></article><article><small>ACTIVE DELIVERY</small><strong>{activeProjects.length}</strong><span>{blocked?blocked+" blocked":"No blocked projects"}</span></article><article><small>CLIENT WAITING</small><strong>{waiting}</strong><span>{waiting?"responses needing attention":proposalWaiting?"proposals awaiting client movement":"Nothing waiting"}</span></article><article><small>READY BRANDS</small><strong>{readyBrands}<em>/{readiness.length}</em></strong><span>contract + payment ready</span></article></section>
 <ExecutiveAttention proposals={proposals} readiness={readiness} agreements={lifecycle.agreements} projects={lifecycle.projects} threads={refs.threadLinks||[]}/>
 <section className="commandColumns"><div><section className="principle commandPrinciple"><strong>Operating rule:</strong> automate routine movement. Surface exceptions, approvals and decisions.</section><OpportunityWorkspace opportunities={opportunities} proposals={proposals} initialOpportunityId={query.opportunity||""}/></div><aside className="todayPanel adminPanel"><div className="todayHead"><div><p className="eyebrow">TODAY</p><h2>Now & Next</h2></div><span className="liveDot">LIVE</span></div><div className="todayList"><div><time>NOW</time><strong>{waiting?waiting+" client response"+(waiting===1?"":"s")+" waiting":proposalWaiting?proposalWaiting+" proposal"+(proposalWaiting===1?"":"s")+" with client":"No client responses waiting"}</strong><small>Commercial attention</small></div><div><time>NEXT</time><strong>{blocked?blocked+" blocked project"+(blocked===1?"":"s"):"Delivery is clear"}</strong><small>Operations</small></div><div><time>READY</time><strong>{readyBrands} brand{readyBrands===1?"":"s"} commissioned</strong><small>Contract + payment readiness</small></div></div><Link className="todayAction" href="/admin/communications">Open communications →</Link></aside></section>
 <LifecycleWorkspace proposals={proposals} agreements={lifecycle.agreements} payments={lifecycle.payments} projects={lifecycle.projects} initialProposalId={query.proposal||""}/>
 <section className="intelligenceDeck"><article className="adminPanel intelligenceCard"><p className="eyebrow">PORTFOLIO INTELLIGENCE</p><h2>Commercial Mix</h2><div className="signalBars">{refs.brands.slice(0,6).map((b:any,i:number)=>{const value=open.filter((o:any)=>o.brand_id===b.id).reduce((n:number,o:any)=>n+Number(o.estimated_value||0),0);const pct=pipelineValue?Math.max(3,Math.round(value/pipelineValue*100)):3;return <div key={b.id}><span>{b.name}</span><i><b style={{width:pct+"%"}}/></i><em>{value?"$"+value.toLocaleString(undefined,{maximumFractionDigits:0}):"—"}</em></div>})}</div></article><article className="adminPanel quickCard"><p className="eyebrow">QUICK ACTIONS</p><h2>Move Work</h2><div className="quickGrid"><Link href="/admin/operations">＋ Project<small>Start delivery</small></Link><Link href="/admin/communications">✉ Conversation<small>Capture context</small></Link><a href="#commercial-forms">◇ Opportunity<small>Build pipeline</small></a><a href="#contracting">✦ Agreement<small>Advance terms</small></a></div></article><article className="adminPanel aiCard"><div className="aiOrb">✦</div><p className="eyebrow">WGOS INTELLIGENCE</p><h2>Ask the system.</h2><p>Search relationships, surface risk, prepare next actions and understand what needs movement.</p><div className="aiPrompt"><span>Try: “What needs my attention?”</span><b>↗</b></div><small>Governed actions · Human approval where required</small></article></section><div id="contracting"><ContractingReadiness rows={readiness}/></div><ClientExperienceReadiness rows={experienceReadiness}/><IntegrationStatus/>
 <RelationshipWorkspace organizations={refs.organizations} contacts={refs.contacts} brands={refs.brands} initialContactId={query.contact||""} initialOrganizationId={query.organization||""} opportunityLinks={refs.opportunityLinks} proposalLinks={refs.proposalLinks} projectLinks={refs.projectLinks} threadLinks={refs.threadLinks} agreementLinks={refs.agreementLinks} paymentLinks={refs.paymentLinks}/>
 <div id="commercial-forms"><CommercialForms brands={refs.brands} organizations={refs.organizations} contacts={refs.contacts} opportunities={opportunities} proposals={proposals} readiness={readiness}/></div></main>;
}