"use client";
import {useEffect,useMemo,useState} from "react";
export default function RelationshipWorkspace({organizations,contacts,brands,initialContactId="",initialOrganizationId="",opportunityLinks,proposalLinks,projectLinks,threadLinks,agreementLinks,paymentLinks}:{organizations:any[];contacts:any[];brands:any[];initialContactId?:string;initialOrganizationId?:string;opportunityLinks:any[];proposalLinks:any[];projectLinks:any[];threadLinks:any[];agreementLinks:any[];paymentLinks:any[]}){
 const [filter,setFilter]=useState("ALL");const [q,setQ]=useState("");const [selected,setSelected]=useState(initialContactId||initialOrganizationId);
 useEffect(()=>{const h=(e:any)=>setFilter(e.detail||"ALL");window.addEventListener("wgos:brand-filter",h);return()=>window.removeEventListener("wgos:brand-filter",h)},[]);
 const brandName=(id:string)=>brands.find(b=>b.id===id)?.name||id;
 const related=(kind:"contact"|"organization",id:string)=>{const key=kind==="contact"?"primary_contact_id":"organization_id";return {opportunities:opportunityLinks.filter(x=>String(x[key]||"")===id),proposals:proposalLinks.filter(x=>String(x[key]||"")===id),projects:projectLinks.filter(x=>String(x[key]||"")===id),threads:threadLinks.filter(x=>String(x[kind==="contact"?"contact_id":"organization_id"]||"")===id),agreements:agreementLinks.filter(x=>String(x[key]||"")===id),payments:paymentLinks.filter(x=>String(x[key]||"")===id)}};
 const timeline=(r:any)=>[...r.opportunities.map((x:any)=>({kind:"OPPORTUNITY",label:x.title||"Opportunity",state:x.stage,at:x.updated_at||x.created_at})),...r.proposals.map((x:any)=>({kind:"PROPOSAL",label:x.opportunity_title||"Proposal",state:x.status,at:x.updated_at||x.created_at})),...r.agreements.map((x:any)=>({kind:"AGREEMENT",label:x.opportunity_title||"Agreement",state:x.status,at:x.updated_at})),...r.payments.map((x:any)=>({kind:"PAYMENT",label:x.opportunity_title||"Payment",state:x.status,at:x.paid_at||x.created_at})),...r.projects.map((x:any)=>({kind:"PROJECT",label:x.title||"Project",state:x.status,at:x.updated_at||x.created_at})),...r.threads.map((x:any)=>({kind:"CONVERSATION",label:x.subject||"Conversation",state:x.status,at:x.updated_at}))].filter((x:any)=>x.at).sort((a:any,b:any)=>new Date(b.at).getTime()-new Date(a.at).getTime()).slice(0,8);
 const match=(x:any)=>filter==="ALL"||(x.brand_ids||[]).includes(filter);
 const orgs=useMemo(()=>organizations.filter(match).filter(o=>(o.name+" "+(o.type||"")).toLowerCase().includes(q.toLowerCase())),[organizations,filter,q]);
 const people=useMemo(()=>contacts.filter(match).filter(c=>(c.first_name+" "+c.last_name+" "+(c.email||"")+" "+(c.organization_name||"")).toLowerCase().includes(q.toLowerCase())),[contacts,filter,q]);const reachable=people.filter(c=>c.email||c.phone).length;const multiBrand=people.filter(c=>(c.brand_ids||[]).length>1).length;
 return <section id="relationships" className="adminPanel relationshipWorkspace">
  <div className="workspaceTitle"><div><p className="eyebrow">RELATIONSHIPS</p><h2>CRM</h2><p className="muted">People and organizations remain global records while their brand relationships stay explicit.</p></div><input aria-label="Search relationships" placeholder="Search people or organizations…" value={q} onChange={e=>setQ(e.target.value)}/></div>
  <div className="relationshipSignals"><span><b>{people.length}</b> PEOPLE</span><span><b>{orgs.length}</b> ORGANIZATIONS</span><span><b>{reachable}</b> REACHABLE</span><span><b>{multiBrand}</b> MULTI-BRAND</span></div><div className="relationshipGrid">
   <div><div className="subhead"><strong>Contacts</strong><span>{people.length}</span></div>{people.length===0?<p className="muted">No contacts match this view.</p>:people.map(c=><article id={"contact-"+c.id} className={"recordCard "+(selected===c.id?"selectedRecord":"")} key={c.id} onClick={()=>setSelected(selected===c.id?"":c.id)}><div className="recordAvatar">{String(c.first_name||"?")[0]}{String(c.last_name||"?")[0]}</div><div><strong>{c.first_name} {c.last_name}</strong><p>{c.role||"Contact"}{c.organization_name?" · "+c.organization_name:""}</p><small>{c.email||c.phone||"No contact method yet"}</small></div><div className="brandChips">{(c.brand_ids||[]).map((id:string)=><span key={id}>{brandName(id)}</span>)}</div>{selected===c.id&&(()=>{const r=related("contact",String(c.id));return <><div className="relationshipGraph"><span><b>{r.opportunities.length}</b> Opportunities</span><span><b>{r.proposals.length}</b> Proposals</span><span><b>{r.projects.length}</b> Projects</span><span><b>{r.threads.length}</b> Conversations</span><span><b>{r.agreements.length}</b> Agreements</span><span><b>{r.payments.length}</b> Payments</span></div><div className="clientTimeline"><div className="timelineHead"><small>CLIENT TIMELINE</small><b>{timeline(r).length?"LATEST ACTIVITY":"NO ACTIVITY YET"}</b></div>{timeline(r).map((e:any,i:number)=><div className="timelineEvent" key={e.kind+e.at+i}><i/><span>{e.kind}</span><strong>{e.label}</strong><em>{e.state||"RECORDED"}</em><time>{new Date(e.at).toLocaleDateString()}</time></div>)}</div><div className="recordContext relationshipContext"><div><small>CONTACT</small><strong>{c.email||c.phone||"No contact method"}</strong></div><div><small>ORGANIZATION</small><strong>{c.organization_name||"Independent / direct"}</strong></div><div><small>BRAND RELATIONSHIPS</small><strong>{(c.brand_ids||[]).length||0}</strong></div><a href="/admin/communications">Open communications →</a></div></>})()}</article>)}</div>
   <div><div className="subhead"><strong>Organizations</strong><span>{orgs.length}</span></div>{orgs.length===0?<p className="muted">No organizations match this view.</p>:orgs.map(o=><article id={"organization-"+o.id} className={"recordCard "+(selected===o.id?"selectedRecord":"")} key={o.id} onClick={()=>setSelected(selected===o.id?"":o.id)}><div className="recordAvatar org">ORG</div><div><strong>{o.name}</strong><p>{o.type||"Organization"}</p><small>{o.website||"No website yet"}</small></div><div className="brandChips">{(o.brand_ids||[]).map((id:string)=><span key={id}>{brandName(id)}</span>)}</div>{selected===o.id&&(()=>{const r=related("organization",String(o.id));return <><div className="relationshipGraph"><span><b>{r.opportunities.length}</b> Opportunities</span><span><b>{r.proposals.length}</b> Proposals</span><span><b>{r.projects.length}</b> Projects</span><span><b>{r.threads.length}</b> Conversations</span></div><div className="recordContext relationshipContext"><div><small>TYPE</small><strong>{o.type||"Organization"}</strong></div><div><small>WEBSITE</small><strong>{o.website||"Not recorded"}</strong></div><div><small>BRAND RELATIONSHIPS</small><strong>{(o.brand_ids||[]).length||0}</strong></div><a href="#commercial">View pipeline →</a></div></>})()}</article>)}</div>
  </div>
 </section>;
}