"use client";
import {useEffect,useMemo,useState} from "react";
export default function RelationshipWorkspace({organizations,contacts,brands,initialContactId="",initialOrganizationId=""}:{organizations:any[];contacts:any[];brands:any[];initialContactId?:string;initialOrganizationId?:string}){
 const [filter,setFilter]=useState("ALL");const [q,setQ]=useState("");const [selected,setSelected]=useState(initialContactId||initialOrganizationId);
 useEffect(()=>{const h=(e:any)=>setFilter(e.detail||"ALL");window.addEventListener("wgos:brand-filter",h);return()=>window.removeEventListener("wgos:brand-filter",h)},[]);
 const brandName=(id:string)=>brands.find(b=>b.id===id)?.name||id;
 const match=(x:any)=>filter==="ALL"||(x.brand_ids||[]).includes(filter);
 const orgs=useMemo(()=>organizations.filter(match).filter(o=>(o.name+" "+(o.type||"")).toLowerCase().includes(q.toLowerCase())),[organizations,filter,q]);
 const people=useMemo(()=>contacts.filter(match).filter(c=>(c.first_name+" "+c.last_name+" "+(c.email||"")+" "+(c.organization_name||"")).toLowerCase().includes(q.toLowerCase())),[contacts,filter,q]);const reachable=people.filter(c=>c.email||c.phone).length;const multiBrand=people.filter(c=>(c.brand_ids||[]).length>1).length;
 return <section id="relationships" className="adminPanel relationshipWorkspace">
  <div className="workspaceTitle"><div><p className="eyebrow">RELATIONSHIPS</p><h2>CRM</h2><p className="muted">People and organizations remain global records while their brand relationships stay explicit.</p></div><input aria-label="Search relationships" placeholder="Search people or organizations…" value={q} onChange={e=>setQ(e.target.value)}/></div>
  <div className="relationshipSignals"><span><b>{people.length}</b> PEOPLE</span><span><b>{orgs.length}</b> ORGANIZATIONS</span><span><b>{reachable}</b> REACHABLE</span><span><b>{multiBrand}</b> MULTI-BRAND</span></div><div className="relationshipGrid">
   <div><div className="subhead"><strong>Contacts</strong><span>{people.length}</span></div>{people.length===0?<p className="muted">No contacts match this view.</p>:people.map(c=><article id={"contact-"+c.id} className={"recordCard "+(selected===c.id?"selectedRecord":"")} key={c.id} onClick={()=>setSelected(selected===c.id?"":c.id)}><div className="recordAvatar">{String(c.first_name||"?")[0]}{String(c.last_name||"?")[0]}</div><div><strong>{c.first_name} {c.last_name}</strong><p>{c.role||"Contact"}{c.organization_name?" · "+c.organization_name:""}</p><small>{c.email||c.phone||"No contact method yet"}</small></div><div className="brandChips">{(c.brand_ids||[]).map((id:string)=><span key={id}>{brandName(id)}</span>)}</div>{selected===c.id&&<div className="recordContext relationshipContext"><div><small>CONTACT</small><strong>{c.email||c.phone||"No contact method"}</strong></div><div><small>ORGANIZATION</small><strong>{c.organization_name||"Independent / direct"}</strong></div><div><small>BRAND RELATIONSHIPS</small><strong>{(c.brand_ids||[]).length||0}</strong></div><a href="/admin/communications">Open communications →</a></div>}</article>)}</div>
   <div><div className="subhead"><strong>Organizations</strong><span>{orgs.length}</span></div>{orgs.length===0?<p className="muted">No organizations match this view.</p>:orgs.map(o=><article id={"organization-"+o.id} className={"recordCard "+(selected===o.id?"selectedRecord":"")} key={o.id} onClick={()=>setSelected(selected===o.id?"":o.id)}><div className="recordAvatar org">ORG</div><div><strong>{o.name}</strong><p>{o.type||"Organization"}</p><small>{o.website||"No website yet"}</small></div><div className="brandChips">{(o.brand_ids||[]).map((id:string)=><span key={id}>{brandName(id)}</span>)}</div>{selected===o.id&&<div className="recordContext relationshipContext"><div><small>TYPE</small><strong>{o.type||"Organization"}</strong></div><div><small>WEBSITE</small><strong>{o.website||"Not recorded"}</strong></div><div><small>BRAND RELATIONSHIPS</small><strong>{(o.brand_ids||[]).length||0}</strong></div><a href="#commercial">View pipeline →</a></div>}</article>)}</div>
  </div>
 </section>;
}