"use client";
import {useMemo,useState} from "react";import {useRouter} from "next/navigation";
const money=(c:any)=>"$"+(Number(c||0)/100).toLocaleString(undefined,{maximumFractionDigits:0});
export default function ContractControlCenter({data,users}:{data:any;users:any[]}){
 const router=useRouter(),[selected,setSelected]=useState(data.controls?.[0]?.id||""),[error,setError]=useState(""),[mode,setMode]=useState("obligation");
 const control:any=data.controls.find((x:any)=>x.id===selected),agreement:any=data.agreements.find((x:any)=>x.control_id===selected);
 const obligations=data.obligations.filter((x:any)=>x.contract_control_id===selected),deliverables=data.deliverables.filter((x:any)=>x.contract_control_id===selected),crew=data.crew.filter((x:any)=>x.contract_control_id===selected),costs=data.costs.filter((x:any)=>x.contract_control_id===selected),changes=data.changes.filter((x:any)=>x.contract_control_id===selected),records=data.records.filter((x:any)=>x.contract_control_id===selected),time=data.time.filter((x:any)=>x.contract_control_id===selected);
 const satisfied=obligations.filter((x:any)=>["SATISFIED","WAIVED","CANCELLED"].includes(x.status)).length,fulfillment=obligations.length?Math.round(satisfied/obligations.length*100):0;
 const projectedRevenue=control?Math.round(Number(control.one_time_total||0)*100):0,collected=control?Math.round(Number(control.collected||0)*100):0,committed=control?Number(control.committed_cost_cents||0)+Number(control.crew_commitment_cents||0):0,projectedProfit=projectedRevenue-committed;
 async function send(body:any){setError("");const r=await fetch("/api/admin/contract-control",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!j.ok){setError(j.error||"Unable to save");return false;}router.refresh();return true;}
 async function submit(e:any){e.preventDefault();const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());body.action=mode;body.controlId=selected;for(const k of ["travelRequired","hotelRequired","immutable"])body[k]=Boolean(body[k]);if(await send(body))e.currentTarget.reset();}
 return <section className="adminPanel" style={{padding:18}}>
  <div className="attentionIntro"><p className="eyebrow">CONTRACT CONTROL PLANE</p><h2>Promise → people → work → evidence → money</h2><p>Operate every signed agreement against its actual obligations, staffing, delivery, records and economics.</p></div>
  {data.agreements.filter((a:any)=>!a.control_id).length>0&&<div style={{display:"grid",gap:8,margin:"14px 0"}}>{data.agreements.filter((a:any)=>!a.control_id).map((a:any)=><div key={a.id} style={{display:"flex",gap:10,justifyContent:"space-between",alignItems:"center",padding:12,border:"1px solid rgba(255,255,255,.08)",borderRadius:12}}><div><strong>{a.brand_name} · {a.opportunity_title||a.title}</strong><small style={{display:"block"}}>SIGNED · ready for Contract Control</small></div><button className="newAction" onClick={()=>send({action:"initialize",agreementId:a.id})}>Initialize control</button></div>)}</div>}
  {data.controls.length===0?<p className="muted">No signed contracts are initialized yet.</p>:<>
   <select value={selected} onChange={e=>setSelected(e.target.value)} style={{margin:"12px 0"}}>{data.controls.map((c:any)=>{const a=data.agreements.find((x:any)=>x.control_id===c.id);return <option key={c.id} value={c.id}>{a?.brand_name} · {a?.opportunity_title||a?.title||"Contract"}</option>})}</select>
   {control&&<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,marginBottom:14}}>
    <article style={{padding:12,border:"1px solid rgba(255,255,255,.08)",borderRadius:12}}><small>FULFILLMENT</small><strong style={{display:"block",fontSize:"1.5rem"}}>{fulfillment}%</strong><span>{satisfied}/{obligations.length} obligations</span></article>
    <article style={{padding:12,border:"1px solid rgba(255,255,255,.08)",borderRadius:12}}><small>CONTRACT VALUE</small><strong style={{display:"block",fontSize:"1.5rem"}}>{money(projectedRevenue)}</strong><span>{money(collected)} collected</span></article>
    <article style={{padding:12,border:"1px solid rgba(255,255,255,.08)",borderRadius:12}}><small>COMMITTED COST</small><strong style={{display:"block",fontSize:"1.5rem"}}>{money(committed)}</strong><span>crew + entered costs</span></article>
    <article style={{padding:12,border:"1px solid rgba(255,255,255,.08)",borderRadius:12}}><small>PROJECTED GROSS</small><strong style={{display:"block",fontSize:"1.5rem"}}>{money(projectedProfit)}</strong><span>{projectedRevenue?Math.round(projectedProfit/projectedRevenue*100):0}% margin</span></article>
   </div>
   <div style={{display:"grid",gap:8,marginBottom:16}}>{obligations.map((o:any)=><div key={o.id} style={{padding:11,border:"1px solid rgba(255,255,255,.07)",borderRadius:10,display:"grid",gridTemplateColumns:"1fr auto",gap:8}}><div><small>{o.responsible_party} · {o.obligation_type} · {o.priority}</small><strong style={{display:"block"}}>{o.title}</strong><span className="muted">{o.due_at?new Date(o.due_at).toLocaleString():"No due date"}{o.owner_name?" · "+o.owner_name:""}</span></div><div style={{display:"flex",gap:6,alignItems:"center",flexWrap:"wrap"}}><select value={o.status} onChange={e=>send({action:"obligation-status",controlId:selected,obligationId:o.id,status:e.target.value})}><option>OPEN</option><option>IN_PROGRESS</option><option>WAITING</option><option>BLOCKED</option><option>SATISFIED</option><option>WAIVED</option><option>BREACHED</option><option>CANCELLED</option></select>{!o.task_id&&agreement?.project_id&&o.responsible_party!=="CLIENT"&&<button onClick={()=>send({action:"obligation-task",controlId:selected,obligationId:o.id})}>Create task</button>}</div></div>)}</div>
   <div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:10}}>{["obligation","deliverable","crew","time","cost","change-order","record"].map(x=><button key={x} className={mode===x?"newAction":""} onClick={()=>setMode(x)}>{x.replace("-"," ")}</button>)}</div>
   <form onSubmit={submit} style={{display:"grid",gap:9}}>
    {mode==="obligation"&&<><input name="title" required placeholder="Obligation title"/><textarea name="description" placeholder="Description"/><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:8}}><select name="obligationType"><option>SERVICE</option><option>DELIVERABLE</option><option>PAYMENT</option><option>CLIENT_INPUT</option><option>STAFFING</option><option>TRAVEL</option><option>DOCUMENT</option><option>APPROVAL</option><option>COMPLIANCE</option><option>OTHER</option></select><select name="responsibleParty"><option>US</option><option>CLIENT</option><option>VENDOR</option><option>SHARED</option></select><select name="priority"><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option><option>LOW</option></select><select name="ownerSubject" defaultValue=""><option value="">No internal owner</option>{users.map((u:any)=><option key={u.auth_user_id} value={u.auth_user_id}>{u.display_name||u.email}</option>)}</select><input name="dueAt" type="datetime-local"/><input name="financialImpact" inputMode="decimal" placeholder="Financial impact $"/></div><input name="sourceClause" placeholder="Source clause / scope reference"/><textarea name="dependencyNotes" placeholder="Dependencies / what must happen first?"/></>}
    {mode==="deliverable"&&<><input name="title" required placeholder="Deliverable"/><input name="clientInputDueAt" type="datetime-local"/><input name="internalDueAt" type="datetime-local"/><input name="clientApprovalDueAt" type="datetime-local"/><input name="finalDueAt" type="datetime-local"/><textarea name="acceptanceCriteria" placeholder="Acceptance criteria"/><textarea name="notes" placeholder="Notes"/></>}
    {mode==="crew"&&<><input name="roleName" required placeholder="Role / instrument / department"/><select name="crewProfileId" defaultValue=""><option value="">Select personnel</option>{data.crewOptions.map((x:any)=><option key={x.crew_profile_id} value={x.crew_profile_id}>{x.first_name} {x.last_name} · {(x.disciplines||[]).join?.(", ")||""}</option>)}</select><select name="bookingStatus"><option>PROPOSED</option><option>INVITED</option><option>HELD</option><option>CONFIRMED</option></select><input name="callAt" type="datetime-local"/><input name="releaseAt" type="datetime-local"/><input name="rehearsalAt" type="datetime-local"/><select name="rateType"><option>FLAT</option><option>HOURLY</option><option>DAY</option><option>WEEKLY</option></select><input name="rate" inputMode="decimal" placeholder="Rate $"/><input name="overtimeRate" inputMode="decimal" placeholder="OT rate $"/><input name="perDiem" inputMode="decimal" placeholder="Per diem $"/><label><input name="travelRequired" type="checkbox"/> Travel</label><label><input name="hotelRequired" type="checkbox"/> Hotel</label><textarea name="notes" placeholder="Booking notes"/></>}
    {mode==="time"&&<><select name="contactId" defaultValue=""><option value="">Worker/contact</option>{data.crewOptions.map((x:any)=><option key={x.contact_id} value={x.contact_id}>{x.first_name} {x.last_name}</option>)}</select><input name="workType" placeholder="Work type" defaultValue="LABOR"/><input name="startedAt" type="datetime-local" required/><input name="endedAt" type="datetime-local" required/><input name="breakMinutes" type="number" min="0" placeholder="Break minutes"/><input name="hourlyRate" inputMode="decimal" placeholder="Hourly rate $"/><textarea name="notes" placeholder="Time notes"/></>}
    {mode==="cost"&&<><select name="costType"><option>LABOR</option><option>RENTAL</option><option>EQUIPMENT</option><option>TRAVEL</option><option>HOTEL</option><option>PER_DIEM</option><option>FREIGHT</option><option>VENDOR</option><option>SUBCONTRACTOR</option><option>PERMIT</option><option>INSURANCE</option><option>MEALS</option><option>MISC</option></select><input name="vendorName" placeholder="Vendor"/><input name="description" required placeholder="Cost description"/><input name="amount" required inputMode="decimal" placeholder="Amount $"/><select name="paymentStatus"><option>UNPAID</option><option>APPROVED</option><option>SCHEDULED</option><option>PAID</option></select><input name="incurredAt" type="datetime-local"/><input name="dueAt" type="datetime-local"/><input name="receiptRef" placeholder="Receipt/file reference"/><textarea name="notes" placeholder="Cost notes"/></>}
    {mode==="change-order"&&<><input name="title" required placeholder="Change order title"/><select name="requestSource"><option>CLIENT</option><option>INTERNAL</option><option>VENDOR</option><option>CONDITION</option></select><textarea name="description" required placeholder="Requested change"/><textarea name="reason" placeholder="Reason / source"/><textarea name="scheduleImpact" placeholder="Schedule impact"/><input name="amountDelta" inputMode="decimal" placeholder="Price change $ (+/-)"/></>}
    {mode==="record"&&<><select name="recordType"><option>AGREEMENT</option><option>SOW</option><option>CHANGE_ORDER</option><option>INVOICE</option><option>PAYMENT</option><option>RECEIPT</option><option>W9</option><option>COI</option><option>PERMIT</option><option>RIDER</option><option>STAGE_PLOT</option><option>INPUT_LIST</option><option>SCHEDULE</option><option>APPROVAL</option><option>DELIVERABLE</option><option>PHOTO</option><option>VIDEO</option><option>EMAIL</option><option>OTHER</option></select><input name="title" required placeholder="Record title"/><input name="artifactRef" placeholder="File/artifact reference"/><input name="externalRef" placeholder="External reference"/><label><input name="immutable" type="checkbox"/> Immutable record</label><textarea name="notes" placeholder="Record notes"/></>}
    {error&&<p>{error}</p>}<button className="newAction" type="submit">Add to contract</button>
   </form>
   <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10,marginTop:16}}><article><small>DELIVERABLES</small><strong style={{display:"block"}}>{deliverables.length}</strong></article><article><small>PERSONNEL</small><strong style={{display:"block"}}>{crew.length}</strong></article><article><small>TIME ENTRIES</small><strong style={{display:"block"}}>{time.length}</strong></article><article><small>COSTS</small><strong style={{display:"block"}}>{costs.length}</strong></article><article><small>CHANGE ORDERS</small><strong style={{display:"block"}}>{changes.length}</strong></article><article><small>RECORDS</small><strong style={{display:"block"}}>{records.length}</strong></article></div>
   {(deliverables.length>0||crew.length>0||time.length>0||costs.length>0||changes.length>0)&&<div style={{display:"grid",gap:12,marginTop:16}}>
    {deliverables.length>0&&<div><h3>Deliverables</h3>{deliverables.map((d:any)=><div key={d.id} style={{display:"flex",justifyContent:"space-between",gap:8,padding:"8px 0",borderBottom:"1px solid rgba(255,255,255,.06)"}}><span>{d.title}{d.final_due_at?" · "+new Date(d.final_due_at).toLocaleDateString():""}</span><select value={d.status} onChange={e=>send({action:"status",controlId:selected,kind:"deliverable",id:d.id,status:e.target.value})}><option>PLANNED</option><option>WAITING_INPUT</option><option>IN_PROGRESS</option><option>CLIENT_REVIEW</option><option>APPROVED</option><option>DELIVERED</option><option>BLOCKED</option><option>CANCELLED</option></select></div>)}</div>}
    {crew.length>0&&<div><h3>Personnel</h3>{crew.map((x:any)=><div key={x.id} style={{display:"grid",gridTemplateColumns:"1fr auto auto",gap:8,padding:"8px 0",borderBottom:"1px solid rgba(255,255,255,.06)"}}><span>{[x.first_name,x.last_name].filter(Boolean).join(" ")||x.role_name} · {x.role_name} · {money(Number(x.rate_cents||0)+Number(x.per_diem_cents||0))}</span><select value={x.booking_status} onChange={e=>send({action:"status",controlId:selected,kind:"crew",id:x.id,status:e.target.value})}><option>PROPOSED</option><option>INVITED</option><option>HELD</option><option>CONFIRMED</option><option>DECLINED</option><option>CANCELLED</option><option>COMPLETED</option></select><select value={x.payment_status} onChange={e=>send({action:"status",controlId:selected,kind:"crew-payment",id:x.id,status:e.target.value})}><option>NOT_DUE</option><option>DUE</option><option>APPROVED</option><option>SCHEDULED</option><option>PAID</option><option>DISPUTED</option></select></div>)}</div>}
    {time.length>0&&<div><h3>Time</h3>{time.map((x:any)=><div key={x.id} style={{display:"flex",justifyContent:"space-between",gap:8,padding:"8px 0",borderBottom:"1px solid rgba(255,255,255,.06)"}}><span>{Number(x.hours||0).toFixed(2)}h · {money(x.labor_cost_cents)} · {x.work_type}</span><select value={x.status} onChange={e=>send({action:"status",controlId:selected,kind:"time",id:x.id,status:e.target.value})}><option>DRAFT</option><option>SUBMITTED</option><option>APPROVED</option><option>REJECTED</option></select></div>)}</div>}
    {costs.length>0&&<div><h3>Costs / AP</h3>{costs.map((x:any)=><div key={x.id} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8,padding:"8px 0",borderBottom:"1px solid rgba(255,255,255,.06)"}}><span>{x.description} · {x.cost_type} · {money(x.amount_cents)}{x.vendor_name?" · "+x.vendor_name:""}</span><select value={x.payment_status} onChange={e=>send({action:"status",controlId:selected,kind:"cost",id:x.id,status:e.target.value})}><option>UNPAID</option><option>APPROVED</option><option>SCHEDULED</option><option>PAID</option><option>DISPUTED</option><option>VOID</option></select></div>)}</div>}
    {changes.length>0&&<div><h3>Change Orders</h3>{changes.map((x:any)=><div key={x.id} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8,padding:"8px 0",borderBottom:"1px solid rgba(255,255,255,.06)"}}><span>{x.title} · {money(x.amount_delta_cents)}</span><select value={x.status} onChange={e=>send({action:"status",controlId:selected,kind:"change-order",id:x.id,status:e.target.value})}><option>DRAFT</option><option>PENDING_CLIENT</option><option>APPROVED</option><option>DECLINED</option><option>CANCELLED</option><option>IMPLEMENTED</option></select></div>)}</div>}
   </div>}
   <Closeout controlId={selected} row={data.closeouts.find((x:any)=>x.contract_control_id===selected)} send={send}/>
   </>}</>}
 </section>;
}
function Closeout({controlId,row,send}:{controlId:string;row:any;send:(b:any)=>Promise<boolean>}){
 const fields=[["finalDeliverablesComplete","Final deliverables",row?.final_deliverables_complete],["finalInvoiceComplete","Final invoice",row?.final_invoice_complete],["clientBalanceZero","Client balance zero",row?.client_balance_zero],["personnelPaid","Personnel paid",row?.personnel_paid],["vendorBalancesZero","Vendors paid",row?.vendor_balances_zero],["rentalsReturned","Rentals returned",row?.rentals_returned],["damageResolved","Damage resolved",row?.damage_resolved],["recordsArchived","Records archived",row?.records_archived],["testimonialRequested","Testimonial requested",row?.testimonial_requested],["referralRequested","Referral requested",row?.referral_requested],["satisfactionRecorded","Satisfaction recorded",row?.satisfaction_recorded],["lessonsRecorded","Lessons recorded",row?.lessons_recorded],["renewalOpportunityReviewed","Renewal reviewed",row?.renewal_opportunity_reviewed]] as const;
 async function submit(e:any){e.preventDefault();const b:any=Object.fromEntries(new FormData(e.currentTarget).entries());for(const [k] of fields)b[k]=Boolean(b[k]);b.action="closeout";b.controlId=controlId;await send(b);}
 return <form onSubmit={submit} style={{display:"grid",gap:8,marginTop:18,padding:14,border:"1px solid rgba(255,255,255,.08)",borderRadius:14}}><div><small>CONTRACT CLOSEOUT</small><h3 style={{margin:"4px 0"}}>{row?.closed_at?"Closed":"Completion checklist"}</h3></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:6}}>{fields.map(([k,label,v])=><label key={k}><input name={k} type="checkbox" defaultChecked={Boolean(v)}/> {label}</label>)}</div><textarea name="notes" defaultValue={row?.notes||""} placeholder="Closeout notes"/><button className="newAction" type="submit">Save closeout</button></form>
}