"use client";
import {useMemo,useState} from "react";import {useRouter} from "next/navigation";
const usd=(c:any)=>"$"+(Number(c||0)/100).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
export default function ExpenseIntelligenceCenter({data}:{data:any}){
 const router=useRouter(),[brand,setBrand]=useState(data.brands?.[0]?.id||""),[mode,setMode]=useState("expense"),[error,setError]=useState("");
 const claims=data.claims.filter((x:any)=>x.brand_id===brand),mileage=data.mileage.filter((x:any)=>x.brand_id===brand),budgets=data.budgets.filter((x:any)=>x.brand_id===brand),rules=data.rules.filter((x:any)=>x.brand_id===brand),forecast=data.forecast.filter((x:any)=>x.brand_id===brand),bank=data.bankInbox.filter((x:any)=>x.brand_id===brand),contracts=data.contracts.filter((x:any)=>x.brand_id===brand),projects=data.projects.filter((x:any)=>x.brand_id===brand);
 const expenseTotal=claims.filter((x:any)=>!["REJECTED","VOID"].includes(x.status)).reduce((n:number,x:any)=>n+Number(x.amount_cents||0),0);
 const mileageTotal=mileage.filter((x:any)=>!["REJECTED","VOID"].includes(x.status)).reduce((n:number,x:any)=>n+Number(x.reimbursement_cents||0),0);
 const pending=claims.filter((x:any)=>x.status==="SUBMITTED").length+mileage.filter((x:any)=>x.status==="SUBMITTED").length;
 const next30=forecast.filter((x:any)=>{const d=new Date(x.forecast_date);return d<=new Date(Date.now()+30*86400000)}).reduce((a:any,x:any)=>({in:a.in+Number(x.inflow_cents||0),out:a.out+Number(x.outflow_cents||0)}),{in:0,out:0});
 async function send(body:any){setError("");const r=await fetch("/api/admin/expense-intelligence",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!j.ok){setError(j.error||"Unable to save");return false;}router.refresh();return true;}
 async function submit(e:any){e.preventDefault();const b:any=Object.fromEntries(new FormData(e.currentTarget).entries());b.action=mode;b.brandId=brand;for(const k of ["reimbursable","billableToClient"])b[k]=Boolean(b[k]);if(await send(b))e.currentTarget.reset();}
 if(!data.brands.length)return null;
 return <section className="adminPanel" style={{padding:18}}>
  <div className="attentionIntro"><p className="eyebrow">EXPENSE INTELLIGENCE</p><h2>Receipts, mileage, reimbursements, budgets and cash flow</h2><p>Capture operational spend once, approve it in WGOS, tie it to the right contract/project, and route the accounting result to the correct entity.</p></div>
  <select value={brand} onChange={e=>setBrand(e.target.value)} style={{margin:"12px 0"}}>{data.brands.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</select>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10,marginBottom:16}}>
   <article><small>EXPENSE CLAIMS</small><strong style={{display:"block",fontSize:"1.4rem"}}>{usd(expenseTotal)}</strong><span>{claims.length} claims</span></article>
   <article><small>MILEAGE</small><strong style={{display:"block",fontSize:"1.4rem"}}>{usd(mileageTotal)}</strong><span>{mileage.length} trips</span></article>
   <article><small>AWAITING APPROVAL</small><strong style={{display:"block",fontSize:"1.4rem"}}>{pending}</strong></article>
   <article><small>30-DAY NET</small><strong style={{display:"block",fontSize:"1.4rem"}}>{usd(next30.in-next30.out)}</strong><span>{usd(next30.in)} in · {usd(next30.out)} out</span></article>
  </div>

  {(claims.length>0||mileage.length>0)&&<div style={{display:"grid",gap:12,marginBottom:16}}>
   {claims.length>0&&<div><h3>Expense claims</h3>{claims.slice(0,12).map((x:any)=><div key={x.id} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8,padding:"9px 0",borderBottom:"1px solid rgba(255,255,255,.06)"}}><div><strong>{x.merchant||x.description}</strong><small style={{display:"block"}}>{x.category} · {usd(x.amount_cents)} · {x.expense_date}{x.receipt_ref?" · receipt attached":""}</small>{x.notes&&<span className="muted">{x.notes}</span>}</div><select value={x.status} onChange={e=>send({action:"claim-status",brandId:brand,kind:"expense",id:x.id,status:e.target.value})}><option>DRAFT</option><option>SUBMITTED</option><option>APPROVED</option><option>REJECTED</option><option>SCHEDULED</option><option>REIMBURSED</option><option>VOID</option></select></div>)}</div>}
   {mileage.length>0&&<div><h3>Mileage claims</h3>{mileage.slice(0,12).map((x:any)=><div key={x.id} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8,padding:"9px 0",borderBottom:"1px solid rgba(255,255,255,.06)"}}><div><strong>{x.origin||"Trip"} → {x.destination||"Destination"}</strong><small style={{display:"block"}}>{Number(x.miles||0).toFixed(1)} mi · {usd(x.reimbursement_cents)} · {x.business_purpose}</small></div><select value={x.status} onChange={e=>send({action:"claim-status",brandId:brand,kind:"mileage",id:x.id,status:e.target.value})}><option>DRAFT</option><option>SUBMITTED</option><option>APPROVED</option><option>REJECTED</option><option>SCHEDULED</option><option>REIMBURSED</option><option>VOID</option></select></div>)}</div>}
  </div>}

  {forecast.length>0&&<div style={{marginBottom:16}}><h3>Cash-flow forecast</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:8}}>{forecast.slice(0,12).map((x:any)=><article key={x.forecast_date} style={{padding:10,border:"1px solid rgba(255,255,255,.06)",borderRadius:10}}><small>{x.forecast_date}</small><strong style={{display:"block"}}>{usd(x.net_cents)}</strong><span>{usd(x.inflow_cents)} in · {usd(x.outflow_cents)} out</span></article>)}</div></div>}

  {bank.length>0&&<div style={{marginBottom:16}}><h3>Bank match inbox</h3>{bank.slice(0,10).map((x:any)=><div key={x.id} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8,padding:"8px 0",borderBottom:"1px solid rgba(255,255,255,.06)"}}><span>{x.posted_date} · {x.description} · {usd(x.amount_cents)} · {x.direction}</span>{x.status!=="MATCHED"&&<button onClick={()=>send({action:"bank-match",brandId:brand,id:x.id})}>Ignore</button>}</div>)}</div>}

  <div style={{display:"flex",gap:6,flexWrap:"wrap",margin:"12px 0"}}>{["expense","mileage","mileage-policy","budget","spend-rule","bank-import"].map(x=><button key={x} className={mode===x?"newAction":""} onClick={()=>setMode(x)}>{x.replace("-"," ")}</button>)}</div>
  <form onSubmit={submit} style={{display:"grid",gap:9}}>
   {(mode==="expense"||mode==="mileage")&&<><select name="controlId" defaultValue=""><option value="">No contract</option>{contracts.map((x:any)=><option key={x.control_id} value={x.control_id}>{x.opportunity_title||x.agreement_title}</option>)}</select><select name="projectId" defaultValue=""><option value="">No project</option>{projects.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select></>}
   {mode==="expense"&&<><input name="merchant" placeholder="Merchant/vendor"/><input name="description" required placeholder="What was purchased?"/><input name="category" placeholder="Category" defaultValue="MISC"/><input name="amount" required inputMode="decimal" placeholder="Amount $"/><input name="expenseDate" type="date"/><input name="receiptRef" placeholder="Receipt file/link reference"/><label><input name="reimbursable" type="checkbox" defaultChecked/> Reimbursable</label><label><input name="billableToClient" type="checkbox"/> Billable to client</label><textarea name="notes" placeholder="Notes"/></>}
   {mode==="mileage"&&<><input name="tripDate" type="date"/><input name="origin" placeholder="Origin"/><input name="destination" placeholder="Destination"/><input name="businessPurpose" required placeholder="Business purpose"/><input name="miles" required inputMode="decimal" placeholder="Miles"/><textarea name="notes" placeholder="Notes"/></>}
   {mode==="mileage-policy"&&<><input name="rateCentsPerMile" type="number" min="0" placeholder="Rate in cents per mile"/><input name="effectiveDate" type="date"/><p className="muted">Keep this configurable rather than hard-coded so your accountant can set the appropriate reimbursement/tax policy for each entity and year.</p></>}
   {mode==="budget"&&<><select name="controlId" defaultValue=""><option value="">Brand-level budget</option>{contracts.map((x:any)=><option key={x.control_id} value={x.control_id}>{x.opportunity_title||x.agreement_title}</option>)}</select><select name="projectId" defaultValue=""><option value="">No project</option>{projects.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select><input name="category" defaultValue="TOTAL" placeholder="Category"/><input name="budget" required inputMode="decimal" placeholder="Budget $"/><input name="warningPct" type="number" defaultValue="80" min="1" max="100" placeholder="Warn at %"/><input name="hardStopPct" type="number" min="1" max="500" placeholder="Escalate at % (optional)"/><textarea name="notes" placeholder="Budget notes"/></>}
   {mode==="spend-rule"&&<><input name="category" placeholder="Category (blank = all spend)"/><input name="threshold" required inputMode="decimal" placeholder="Approval required over $"/><select name="approverSubject" defaultValue=""><option value="">Select approver</option>{data.users.map((u:any)=><option key={u.auth_user_id} value={u.auth_user_id}>{u.display_name||u.email}</option>)}</select><textarea name="notes" placeholder="Approval rule notes"/></>}
   {mode==="bank-import"&&<><input name="provider" defaultValue="MANUAL" placeholder="Bank/provider"/><input name="externalAccountId" placeholder="Account reference"/><input name="externalTransactionId" placeholder="Transaction ID (optional)"/><input name="postedDate" type="date"/><input name="description" required placeholder="Bank description"/><input name="amount" required inputMode="decimal" placeholder="Amount $"/><select name="direction"><option>OUTFLOW</option><option>INFLOW</option></select><p className="muted">This inbox is provider-neutral. Later a bank feed can populate the same structure automatically and WGOS can suggest matches to invoices, expenses, reimbursements and vendor payments.</p></>}
   {error&&<p>{error}</p>}<button className="newAction" type="submit">Save</button>
  </form>

  {(budgets.length>0||rules.length>0)&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:12,marginTop:16}}>
   <div><h3>Budgets</h3>{budgets.map((x:any)=><p key={x.id}>{x.category} · {usd(x.budget_cents)} · warn {x.warning_pct}%{x.hard_stop_pct?" · escalate "+x.hard_stop_pct+"%":""}</p>)}</div>
   <div><h3>Approval rules</h3>{rules.map((x:any)=><p key={x.id}>{x.category||"All spend"} over {usd(x.threshold_cents)} → {x.approver_name||"assigned approver"}</p>)}</div>
  </div>}
 </section>;
}