-- DEPRECATED BOOTSTRAP REFERENCE ONLY
-- DO NOT APPLY TO PRODUCTION.
-- The live Neon wgos schema is authoritative; applied migrations are consolidated under database/migrations/.
-- This starter model remains temporarily for historical comparison and will be retired after full migration consolidation.

-- WGOS canonical schema v1
create extension if not exists pgcrypto;
create table brands(id text primary key,name text not null,public_domain text not null,legal_type text not null,owned boolean not null default true,created_at timestamptz not null default now());
create table people(id uuid primary key default gen_random_uuid(),first_name text not null,last_name text not null,email text,phone text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table organizations(id uuid primary key default gen_random_uuid(),name text not null,website text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table person_brands(person_id uuid references people(id) on delete cascade,brand_id text references brands(id) on delete cascade,primary key(person_id,brand_id));
create table organization_brands(organization_id uuid references organizations(id) on delete cascade,brand_id text references brands(id) on delete cascade,primary key(organization_id,brand_id));
create table opportunities(id uuid primary key default gen_random_uuid(),brand_id text not null references brands(id),person_id uuid references people(id),organization_id uuid references organizations(id),title text not null,stage text not null check(stage in('lead','discovery','qualified','proposal','negotiation','won','lost')),value_cents bigint not null default 0,currency text not null default 'USD',owner_id text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table proposals(id uuid primary key default gen_random_uuid(),opportunity_id uuid not null references opportunities(id),brand_id text not null references brands(id),public_path text not null,status text not null default 'draft',total_cents bigint not null default 0,created_at timestamptz not null default now());
create table projects(id uuid primary key default gen_random_uuid(),brand_id text not null references brands(id),opportunity_id uuid references opportunities(id),name text not null,status text not null default 'planning',start_at timestamptz,end_at timestamptz,created_at timestamptz not null default now());
create table tasks(id uuid primary key default gen_random_uuid(),brand_id text not null references brands(id),project_id uuid references projects(id),title text not null,status text not null default 'open',assignee_id text,due_at timestamptz,created_at timestamptz not null default now());
create table activity(id uuid primary key default gen_random_uuid(),brand_id text references brands(id),actor_id text,entity_type text not null,entity_id text not null,action text not null,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index opportunities_brand_stage_idx on opportunities(brand_id,stage);create index tasks_brand_due_idx on tasks(brand_id,due_at);create index activity_entity_idx on activity(entity_type,entity_id,created_at desc);
insert into brands(id,name,public_domain,legal_type,owned) values ('studio2016','Studio2016','studio2016.com','sole_proprietorship',true),('jermaine-williams','Jermaine Williams','jermainewilliams.com','sole_proprietorship',true),('charmin-greene','Charmin Greene','charmingreene.com','sole_proprietorship',true),('charmin-jermaine','Charmin & Jermaine','charminjermaine.com','partnership',true),('cg-success','CG Success','cgsuccessenterprise.com','sole_proprietorship',true),('sound-legacy','Sound Legacy Institute','soundlegacyinstitute.com','nonprofit',true),('dionnes-boutique','Dionne''s Boutique','','sole_proprietorship',true) on conflict do nothing;