export const CG_SUCCESS_MASTER_TERMS_TITLE="CG_SUCCESS — MASTER CONSULTING, COACHING & PROFESSIONAL SERVICES AGREEMENT";
export const CG_SUCCESS_MASTER_TERMS_VERSION="2026.1";
export const CG_SUCCESS_MASTER_TERMS_2026_1=`CG_SUCCESS
MASTER CONSULTING, COACHING & PROFESSIONAL SERVICES AGREEMENT
Texas Master Terms
Version: 2026.1
Effective Date: [______]

This Master Agreement governs Services provided by CG Success (“CG Success”) to the client identified in an accepted SOW (“Client”). Each is a “Party”; together, the “Parties.”

1. PURPOSE; CONTRACT STRUCTURE. This Agreement establishes legal, commercial, operational, IP, safety, payment, equipment, production, and risk-allocation terms. Project-specific scope, fees, schedule, deliverables, equipment, and special terms belong in an SOW. CG Success is the sole provider party unless an executed SOW expressly states otherwise. Its owner, principals, affiliated brands, personnel, contractors, vendors, manufacturers, and production partners are not guarantors or co-obligors merely because they support a Project. No individual personally guarantees performance absent an express written personal guaranty. CG Success may assign this Agreement to a successor entity that assumes its obligations where permitted by law.

2. DEFINITIONS. “SOW” includes an accepted statement of work, proposal, booking confirmation, order, rental order, or other engagement document incorporating this Agreement. “Services” means only services expressly included in an SOW. “Equipment” means audio, video, broadcast, LED, lighting, networking, communications, computing, power-distribution, cabling, staging-related, backline, or other equipment supplied, rented, procured, integrated, or handled for a Project. “Background IP” includes CG Success’s pre-existing or independently developed systems, designs, templates, drawings, workflows, programming, show files, code, methods, documentation, and know-how. “Change Order” means an accepted written or authenticated electronic modification. “Client Materials” means materials, information, files, plans, credentials, content, or instructions supplied or directed by Client.

3. SERVICES; EXCLUSIONS. Services may include production management; audio; video; broadcast; LED; lighting; RF; communications; networking; playback; backline; staging coordination; systems architecture; consulting; design; engineering coordination; installation; integration; programming; commissioning; training; rentals; procurement; creative/technical direction; and documentation. Anything not expressly included is excluded, including unlisted labor, equipment, engineering stamps, permits, licenses, structural/electrical work, rehearsals, recording rights, freight, or expenses. CG Success will perform professionally but does not guarantee attendance, audience response, fundraising, sales, broadcast reach, platform performance, uninterrupted third-party services, or other outcomes outside reasonable control.

4. ORDER OF PRECEDENCE. Conflicts are resolved by: (1) SOW special terms expressly modifying a provision; (2) accepted Addenda; (3) this Agreement; (4) incorporated Riders/specifications/drawings; (5) accepted Change Orders according to their stated effect. Client purchase orders, venue forms, portal terms, emails, texts, or conversations do not modify this Agreement merely by receipt or performance. Modification requires affirmative acceptance by an Authorized Representative.

5. BOOKING; PROJECT COMMENCEMENT. No date, crew, inventory, design capacity, procurement commitment, or production capacity is reserved until required acceptance, payment, and stated booking requirements are complete. Temporary holds expire as stated. Client shall provide materially accurate Project, site, venue, attendance, schedule, power, rigging, network, structural, security, access, and production information. Material omissions or changed conditions may require repricing, redesign, added labor/equipment, schedule changes, or a Change Order.

6. FEES; PAYMENT. Client shall pay the SOW price and milestones. CG Success may require remaining balances before deployment, delivery, installation, performance, transfer of deliverables, or Equipment release. Past-due amounts may accrue the lesser of the SOW rate or maximum lawful rate plus recoverable collection costs. Except where prohibited, undisputed amounts may not be offset for unrelated claims. Subject to required notice/cure, CG Success may suspend design, procurement, preparation, crew, delivery, installation, deliverables, or performance for nonpayment without waiving amounts due. Client shall provide reasonable written notice of a good-faith payment dispute before chargeback except where law/network rules provide otherwise; knowingly improper chargebacks are material breach.

7. TAXES; FREIGHT; EXPENSES. Client shall pay legally chargeable transaction taxes and SOW-allocated freight, shipping, delivery, permit, customs, travel, and reimbursable expenses. CG Success remains responsible for taxes on its own income.

8. PERSONNEL; PROFESSIONAL ROLES. CG Success may select and reasonably substitute qualified personnel, subcontractors, vendors, manufacturers, and production partners. No CG Success worker becomes Client’s employee merely by participating. Where law requires a licensed engineer, electrician, rigger, architect, contractor, or other professional, CG Success may coordinate that work but does not represent itself as holding a license it does not hold. Licensed-professional services/stamped documents are excluded unless expressly included.

9. DESIGN BASIS; ASSUMPTIONS. Designs, recommendations, budgets, drawings, signal flows, equipment selections, coverage concepts, and architectures may rely on Client/venue/architect/engineer/manufacturer information. Client shall disclose known constraints and provide accurate existing-condition information. CG Success may revise design, price, schedule, equipment, or scope when field, structural, electrical, code, RF, network, manufacturer, venue, or other material facts differ from assumptions. Concept drawings/renderings/budgets are not stamped engineering, construction documents, or guarantees of field conditions unless expressly stated.

10. CLIENT; VENUE; SITE RESPONSIBILITIES. Client shall provide or cause lawful/timely access, safe work areas, allocated permits/approvals, accurate drawings/site information, loading/parking, suitable work surfaces/staging, agreed electrical service, qualified grounding/bonding, allocated network/internet, security, weather protection, crowd management, and cooperation from Client-controlled venues/trades/vendors.

11. ELECTRICAL; STRUCTURAL; RIGGING; LIFE SAFETY. Unless expressly included and performed by appropriately qualified persons, CG Success does not assume responsibility for building electrical systems, structural engineering, roof capacity, permanent rigging points, fire/life-safety systems, code compliance of preexisting conditions, or Client/Venue trade work. Client/Venue shall provide verified structural/electrical capacity where reasonably required. CG Success review/use of third-party power, structures, rigging points, lifts, stages, roofs, truss, or plans does not make CG Success the structural engineer, electrician, AHJ, safety inspector, or guarantor. CG Success may refuse to hang, energize, install, or operate under unsafe, materially undocumented, or nonconforming conditions.

12. THIRD-PARTY PRODUCTION. Client/Venue/third-party suppliers remain responsible for their personnel, equipment, staging, power, rigging, networking, internet, engineering, installation, maintenance, operation, and safety. Material deficiency permits CG Success reasonably to request correction, modify Services, delay commencement, or exercise safety rights.

13. SAFETY; SECURITY. CG Success may delay, modify, relocate, de-energize, suspend, or discontinue activity when it reasonably believes a material threat exists to persons, Equipment, structures, data, or property, including severe weather, electrical/structural/rigging hazards, fire, violence, uncontrolled crowds, dangerous intoxication, inadequate security, or comparable objectively reasonable concerns. When practicable, Client/Venue may cure remediable conditions. Financial responsibility follows cause/responsibility under the Agreement, not merely which Party stopped work.

14. OUTDOOR EVENTS; WEATHER. Client shall provide agreed weather, ballast, drainage, climate, and environmental protection. CG Success need not expose persons or Equipment to unsafe/materially damaging conditions. Force Majeure weather is governed below. Foreseeable conditions for which Client agreed but failed to provide protection may be Client default.

15. EQUIPMENT RENTAL; CUSTODY. Equipment remains its owner’s property unless sold. Client shall use rentals only as intended and shall not sell, pledge, sublease, materially modify, open, repair, relocate beyond approved locations, or permit unauthorized operation. Custody transfers as stated in the SOW/delivery record. While in Client custody/control, Client shall exercise reasonable care/security/environmental protection and promptly report loss, theft, seizure, damage, malfunction, or casualty. To the extent legally attributable to Client, Client is responsible for repair cost or reasonable replacement value beyond ordinary wear, excluding inherent defect, ordinary failure, or CG Success responsibility. Holdover/late-return charges may apply as agreed.

16. SALES; PROCUREMENT; MANUFACTURERS. Procurement is subject to manufacturer availability, allocation, discontinuation, lead times, freight, tariffs, substitutions, and price changes outside reasonable control. Material substitutions require Client approval. Transferable manufacturer warranties pass through to Client; CG Success does not enlarge them unless expressly stated. Special-order, custom, configured, licensed, or opened items may be nonreturnable as stated and permitted by law.

17. INSTALLATION; EXISTING SYSTEMS. Existing systems may contain latent defects, undocumented wiring, obsolete firmware, incompatible protocols, inadequate power, network restrictions, or other previously undiscoverable conditions. Discovery may require Change Order. Unless included, CG Success is not responsible for unrelated existing-system defects. Client shall not materially alter an engineered/commissioned system before acceptance without notice; unauthorized changes may require retesting and may limit responsibility for resulting malfunction.

18. TESTING; COMMISSIONING; ACCEPTANCE. Acceptance criteria shall be stated where applicable. Included testing, commissioning, tuning, training, punch-list review, and documentation will be performed as specified. Minor punch-list items not materially preventing intended use do not reject the whole Project. Client shall identify claimed material nonconformities within any stated acceptance period with reasonable specificity and allow CG Success reasonable inspection/cure before engaging another provider at CG Success expense, except genuine emergency.

19. NETWORKS; SOFTWARE; CYBER. Unless expressly included, CG Success does not guarantee internet/cellular/cloud/streaming platforms, third-party software/firmware/APIs/licenses/accounts, cybersecurity, or external networks. Client controls its credentials/permissions. CG Success is not responsible for outages, platform changes, account suspensions, cyber incidents, or vulnerabilities originating outside reasonable control. No system is represented as absolutely secure or failure-proof.

20. MEDIA; THIRD-PARTY RIGHTS. Providing production technology does not itself grant music, performance, synchronization, publicity, trademark, broadcast, content, or distribution rights. Client is responsible for rights allocated to Client for content it directs CG Success to capture, display, transmit, reproduce, or distribute. CG Success grants no third-party rights it does not own.

21. AI; DIGITAL REPLICAS. Neither Party receives rights merely through the engagement to train/fine-tune AI on the other Party’s protected nonpublic materials, create unauthorized digital replicas/synthetic identities, build biometric datasets, or falsely imply endorsement. Client shall not direct unlawful/unauthorized synthetic exploitation of third parties. Ordinary authorized technical automation for editing, delivery, accessibility, search, security, or distribution is not prohibited unless used for prohibited exploitation.

22. INTELLECTUAL PROPERTY. Each Party retains pre-existing IP. Unless expressly assigned in a separate writing, CG Success retains Background IP including system concepts, signal-flow methods, drawings, templates, show files, programming methods, network architectures, control logic, workflows, production methods, documentation frameworks, software/configuration methods, technical designs, and know-how. Client retains Client Materials and represents it has rights necessary for directed use. Commissioned-deliverable ownership/license is stated in the SOW/Addendum; payment alone does not automatically assign IP.

23. CONFIDENTIALITY. Each Party shall reasonably protect material nonpublic information including pricing, unreleased content, credentials, networks, security plans, show files, technical designs, private guest information, business methods, personnel information, and Project details. Exceptions include information public without breach, independently developed, rightfully obtained elsewhere, or legally required. Legally compelled disclosure may be made subject to legally permissible notice.

24. SCHEDULE; DELAYS; OVERTIME. SOW access, load-in, installation, rehearsal, soundcheck, doors, show, strike, pickup, commissioning, and curfew times are material. Client/Venue-caused delay does not automatically extend end time or waive overtime, labor, standby, remobilization, freight, or resulting charges. CG Success will reasonably attempt accommodation subject to personnel/equipment/transport/venue constraints. Overtime requires authorization and applicable fees/availability.

25. CHANGE ORDERS. Material scope changes require written/electronic approval and may affect price, schedule, equipment, design, labor, engineering, permits, freight, procurement, travel, testing, and availability. Authenticated WGOS approval may satisfy this requirement. Emergency field conditions may require immediate protective action; material scope/cost effects shall be documented as practicable. One accommodation creates no ongoing uncompensated obligation.

26. CLIENT CANCELLATION. Cancellation must be written. The SOW states any cancellation schedule. In addition to amounts properly due under an enforceable schedule, Client remains responsible to the extent permitted by law for performed Services, completed design/preparation, authorized nonrecoverable travel/freight, crew commitments, custom fabrication/configuration, special-order procurement, rentals, subcontractor commitments, restocking/cancellation charges, and other authorized nonrecoverable obligations, without duplicate recovery. Where identified as liquidated damages, amounts are intended as a reasonable forecast of difficult-to-determine anticipated losses including reserved capacity/displaced opportunities, not a penalty, only to the extent enforceable.

27. POSTPONEMENT. Postponement requires written approval. CG Success will reasonably consider replacement dates but does not guarantee personnel, inventory, vendor, venue, or Equipment availability. Client remains responsible for additional/nonrecoverable postponement costs. An unaccommodated postponement may be treated under cancellation terms unless otherwise agreed.

28. FORCE MAJEURE. Neither Party is liable for failure/delay caused by circumstances beyond reasonable control materially preventing, making unlawful, or making unsafe performance, including natural disaster, severe weather, fire, flood, epidemic restrictions, war, terrorism, civil disorder, governmental order, transportation disruption, widespread utility/network failure, venue destruction, non-caused labor disruption, supply embargo, or comparable events. The affected Party shall provide practicable notice and commercially reasonable mitigation. Parties shall reasonably explore rescheduling. CG Success need not absorb completed work or authorized nonrecoverable commitments. Reconciliation considers performed Services, transferable/recoverable commitments, SOW terms, and law without windfall/duplicate recovery.

29. CG_SUCCESS CANCELLATION. If CG Success cancels for reasons within reasonable control without agreed substitute, cure, or reschedule, it shall refund amounts paid for unperformed Services subject to remedies that cannot lawfully be limited. CG Success receives no Client cancellation damages when CG Success wrongfully cancels.

30. CLIENT DEFAULT. Material default may include nonpayment, material misrepresentation, denied access, failure to provide agreed site/power/structural/rigging/production/safety/security/infrastructure, unlawful instructions, unauthorized Equipment use, expanded scope without agreement, dangerous/abusive conduct, interference with safe operations, or other material breach. Where reasonably curable, Client receives a reasonable opportunity considering Project timing. If uncured, CG Success may suspend/terminate Services, secure/de-energize Equipment where reasonably necessary, recover its property as permitted by law, and pursue remedies.

31. REPRESENTATIONS; AUTHORITY. Each Party represents authority to enter the engagement, reasonably sufficient authority of its accepting representative, no knowing violation of another binding agreement, and compliance with laws materially applicable to its own obligations. Client represents authority to grant agreed access to sites, systems, Client Materials, credentials, and equipment.

32. INDEPENDENT CONTRACTOR. CG Success is an independent contractor. Nothing creates employment, agency, fiduciary, franchise, joint venture, or partnership with Client. CG Success controls means/methods subject to agreed requirements, law, and safety.

33. THIRD-PARTY PROVIDERS. CG Success may engage subcontractors, technicians, vendors, manufacturers, rental houses, carriers, and production partners. Unless Client separately contracts directly with a provider, CG Success remains responsible for its contractual obligations subject to this Agreement. CG Success is not responsible for independent providers separately selected/contracted by Client/Venue.

34. INDEMNIFICATION. To the extent permitted by law, Client shall defend, indemnify, and hold harmless CG Success and its owners/principals/personnel/representatives from third-party claims, damages, liabilities, judgments, and reasonable defense costs to the extent arising from Client negligence/willful misconduct, material breach, infringing Client Materials/instructions, site/venue/structural/electrical/network/security/crowd/infrastructure conditions allocated to Client, unauthorized Equipment use/modification, or Client-controlled contractors/vendors, except to the extent caused by an indemnified party’s own responsibility that law does not permit shifted. CG Success shall similarly defend/indemnify Client for third-party claims to the extent arising from CG Success negligence/willful misconduct, material breach, or infringing CG Success-provided materials, except to the extent caused by Client/responsible persons. Prompt notice, qualified defense control, reasonable cooperation, and consent to settlements imposing admission/nonmonetary obligation/unreimbursed liability apply.

35. LIMITATION OF LIABILITY. To the maximum extent permitted by law, neither Party is liable to the other for indirect, incidental, special, exemplary, punitive, or consequential damages, including speculative lost profits, donations, ticket sales, audience, reputation, or opportunities. CG Success aggregate contractual liability arising from a particular SOW shall not exceed fees paid/payable under that SOW. Limitations do not apply where law prohibits and may have SOW carve-outs. No duplicate recovery.

36. INSURANCE. Insurance, certificates, waivers, and additional-insured requirements shall be stated in the SOW/Rider. Insurance availability does not enlarge contractual liability.

37. DAMAGE; LOSS; THEFT. Each Party is responsible to the extent permitted by law for physical loss/damage legally attributable to it. Client is responsible for CG Success-controlled Equipment loss/damage/theft legally attributable to Client, its personnel/vendors/guests, or conditions under Client responsibility. Ordinary wear, inherent defect, CG Success-caused damage, and ordinary equipment failure remain CG Success responsibility.

38. WARRANTIES; DISCLAIMER. CG Success warrants professional Services and express SOW warranties. Except express warranties and nonwaivable rights, CG Success makes no implied guarantee concerning third-party products, uninterrupted operation, compatibility with undisclosed systems, future manufacturer/platform support, or fitness for undisclosed uses.

39. CLIENT MODIFICATIONS. CG Success is not responsible for failures caused by unauthorized modification, relocation, reprogramming, rewiring, firmware/credential changes, misuse, improper maintenance, third-party repair, incompatible additions, or operation contrary to documentation after delivery/commissioning. Diagnosis/restoration/recommissioning caused by such intervention may be charged.

40. DATA; FILES; BACKUPS. Unless expressly included, Client is responsible for archival backups of Client-owned media, recordings, configurations, credentials, and data after delivery. CG Success may maintain working/project records for operational, legal, backup, and portfolio purposes subject to confidentiality/rights. No indefinite retention obligation exists unless stated.

41. PUBLICITY; PORTFOLIO. No engagement grants endorsement rights. Each Party retains names/marks. CG Success may truthfully identify Client/Project in professional history and use nonconfidential documentation of its work for portfolio/marketing unless SOW/confidentiality prohibits. Uses implying broader endorsement/sponsorship require approval.

42. DISPUTE ESCALATION. Authorized Representatives shall first attempt good-faith business resolution. If unresolved, either Party may request confidential mediation in Harris County, Texas. Unless urgent relief is reasonably necessary, mediation precedes final arbitration.

43. BINDING ARBITRATION. Except expressly excluded matters, unresolved disputes arising from this Agreement/SOW shall be resolved by binding arbitration administered by the American Arbitration Association under applicable commercial rules unless otherwise agreed. The Federal Arbitration Act governs the arbitration agreement where applicable; Texas substantive law governs merits except where federal law controls. Seat: Harris County, Texas. One neutral arbitrator unless rules/agreement require otherwise. Discovery shall be proportional. The arbitrator may award lawful Agreement remedies but not rewrite the substantive bargain beyond authority. Nonpublic proceedings/materials remain confidential to the extent lawful subject to necessary disclosures. Either Party may seek temporary/preliminary/injunctive/equitable court relief reasonably necessary to protect IP, confidential information, safety, property, payment security, Equipment, or status quo pending arbitration without waiver. A reasoned written award may be requested as permitted; judgment may be entered by a court with jurisdiction.

44. ATTORNEYS’ FEES; COSTS. Fees, arbitration expenses, court costs, and dispute-related costs may be awarded to the extent authorized by this Agreement, applicable law, or rules.

45. GOVERNING LAW. Texas substantive law governs without regard to conflicts principles except where applicable federal law controls.

46. NOTICES. Formal legal notices go to SOW-designated or later written notice destinations. Operational communications may occur through WGOS, email, text, or production systems. Routine operational communication is not automatically formal legal notice where formal notice is required.

47. ELECTRONIC TRANSACTIONS; WGOS RECORDS. Parties consent to electronic transactions to the extent permitted by law. Electronic signatures, authenticated approvals, timestamps, payment records, identity evidence, audit trails, document versions, delivery records, Equipment custody records, and other reliable electronic evidence may establish execution, acceptance, attribution, modification, delivery, custody, or performance. CG Success may maintain authoritative records through WGOS or successor platform. Electronic acceptance does not diminish legal requirements.

48. ASSIGNMENT; SUCCESSORS. Client may not assign in a manner materially changing Project, counterparty risk, site, conditions, or CG Success obligations without written consent. CG Success may assign to a successor in reorganization, incorporation, conversion, merger, sale, or transfer of substantially all relevant operations if the successor assumes obligations.

49. THIRD-PARTY BENEFICIARIES; NONEXCLUSIVITY. Except persons expressly protected by indemnity/liability provisions, no third-party rights are created. Unless stated, neither Party grants exclusivity. CG Success may serve other clients, including competitors, subject to confidentiality.

50. NO WAIVER; SEVERABILITY; REFORMATION. Delay/failure enforcing a right is not waiver. A waiver is matter-specific unless stated. Invalid/unenforceable provisions do not defeat remaining terms. Where lawful, an unenforceable provision shall be reformed only minimally to preserve lawful intent.

51. SURVIVAL; ENTIRE AGREEMENT; AMENDMENTS. Payment, Equipment/property rights, IP, confidentiality, media/data rights, indemnity, liability limits, dispute resolution, and accrued rights survive as appropriate. This Agreement with SOW, accepted Addenda, incorporated Riders/specifications/drawings, and Change Orders is the entire engagement agreement and supersedes prior/contemporaneous representations on the subject, except where law provides otherwise. Amendments require Authorized Representatives in writing/authenticated electronic process; operational personnel cannot modify terms merely through conversation.

52. COUNTERPARTS; INTERPRETATION; ACCEPTANCE. Documents may be executed in counterparts/electronically. Headings are convenience only. “Include/including” mean without limitation unless context requires. Singular includes plural where appropriate. No presumption against drafter applies merely because one Party prepared the document to the extent permitted by law. Executing an incorporating SOW acknowledges receipt/reasonable access and agreement to these terms. Separate execution may also be used.

OPTIONAL SIGNATURE PAGE
CLIENT
Legal Name: __________________________________
Authorized Representative: _____________________
Title: _______________________________________
Signature: ___________________________________
Date: _______________________________________

CG_SUCCESS
By its Authorized Representative:
Name: _______________________________________
Title/Capacity: _______________________________
Signature: ___________________________________
Date: _______________________________________
`;
