import "server-only";
import {db} from "./db";

export async function globalSearch(q:string,brandId?:string){
 const term=q.trim();if(term.length<2)return [];
 const sql=db();const like="%"+term+"%";
 const [contacts,orgs,opps,projects,tasks,assets,proposals]=await Promise.all([
  brandId?sql`SELECT DISTINCT c.id::text,'CONTACT' kind,concat(c.first_name,' ',c.last_name) title,c.email subtitle,cb.brand_id FROM wgos.contacts c JOIN wgos.contact_brands cb ON cb.contact_id=c.id WHERE cb.brand_id=${brandId} AND (concat(c.first_name,' ',c.last_name) ILIKE ${like} OR c.email ILIKE ${like}) LIMIT 20`:sql`SELECT id::text,'CONTACT' kind,concat(first_name,' ',last_name) title,email subtitle,NULL::text brand_id FROM wgos.contacts WHERE concat(first_name,' ',last_name) ILIKE ${like} OR email ILIKE ${like} LIMIT 20`,
  brandId?sql`SELECT DISTINCT o.id::text,'ORGANIZATION' kind,o.name title,o.website subtitle,ob.brand_id FROM wgos.organizations o JOIN wgos.organization_brands ob ON ob.organization_id=o.id WHERE ob.brand_id=${brandId} AND o.name ILIKE ${like} LIMIT 20`:sql`SELECT id::text,'ORGANIZATION' kind,name title,website subtitle,NULL::text brand_id FROM wgos.organizations WHERE name ILIKE ${like} LIMIT 20`,
  brandId?sql`SELECT id::text,'OPPORTUNITY' kind,title,stage subtitle,brand_id FROM wgos.opportunities WHERE brand_id=${brandId} AND title ILIKE ${like} LIMIT 20`:sql`SELECT id::text,'OPPORTUNITY' kind,title,stage subtitle,brand_id FROM wgos.opportunities WHERE title ILIKE ${like} LIMIT 20`,
  brandId?sql`SELECT id::text,'PROJECT' kind,title,status subtitle,brand_id FROM wgos.projects WHERE brand_id=${brandId} AND title ILIKE ${like} LIMIT 20`:sql`SELECT id::text,'PROJECT' kind,title,status subtitle,brand_id FROM wgos.projects WHERE title ILIKE ${like} LIMIT 20`,
  brandId?sql`SELECT t.id::text,'TASK' kind,t.title,t.status subtitle,p.brand_id,t.project_id::text parent_id FROM wgos.tasks t JOIN wgos.projects p ON p.id=t.project_id WHERE p.brand_id=${brandId} AND t.title ILIKE ${like} LIMIT 20`:sql`SELECT t.id::text,'TASK' kind,t.title,t.status subtitle,p.brand_id,t.project_id::text parent_id FROM wgos.tasks t JOIN wgos.projects p ON p.id=t.project_id WHERE t.title ILIKE ${like} LIMIT 20`,
  brandId?sql`SELECT id::text,'ASSET' kind,COALESCE(NULLIF(trim(concat_ws(' ',manufacturer,model)),''),category) title,status subtitle,brand_id FROM wgos.equipment_assets WHERE brand_id=${brandId} AND (category ILIKE ${like} OR manufacturer ILIKE ${like} OR model ILIKE ${like} OR asset_tag ILIKE ${like}) LIMIT 20`:sql`SELECT id::text,'ASSET' kind,COALESCE(NULLIF(trim(concat_ws(' ',manufacturer,model)),''),category) title,status subtitle,brand_id FROM wgos.equipment_assets WHERE category ILIKE ${like} OR manufacturer ILIKE ${like} OR model ILIKE ${like} OR asset_tag ILIKE ${like} LIMIT 20`,
  brandId?sql`SELECT p.id::text,'PROPOSAL' kind,COALESCE(o.title,'Proposal') title,concat('v',p.version,' · ',p.status) subtitle,p.brand_id FROM wgos.proposals p LEFT JOIN wgos.opportunities o ON o.id=p.opportunity_id WHERE p.brand_id=${brandId} AND (COALESCE(o.title,'') ILIKE ${like} OR p.status ILIKE ${like}) LIMIT 20`:sql`SELECT p.id::text,'PROPOSAL' kind,COALESCE(o.title,'Proposal') title,concat('v',p.version,' · ',p.status) subtitle,p.brand_id FROM wgos.proposals p LEFT JOIN wgos.opportunities o ON o.id=p.opportunity_id WHERE COALESCE(o.title,'') ILIKE ${like} OR p.status ILIKE ${like} LIMIT 20`
 ]);
 return [...contacts,...orgs,...opps,...proposals,...projects,...tasks,...assets];
}
export async function executiveMetrics(){const sql=db();const [commercial,delivery]=await Promise.all([
 sql`SELECT brand_id,count(*) FILTER(WHERE stage NOT IN ('WON','LOST'))::int open_opportunities,COALESCE(sum(estimated_value) FILTER(WHERE stage NOT IN ('WON','LOST')),0)::numeric open_pipeline_value,count(*) FILTER(WHERE stage='WON')::int won_count FROM wgos.opportunities GROUP BY brand_id`,
 sql`SELECT brand_id,count(*) FILTER(WHERE status IN ('ACTIVE','PLANNING','BLOCKED'))::int active_projects,count(*) FILTER(WHERE status='BLOCKED')::int blocked_projects FROM wgos.projects GROUP BY brand_id`]);return {commercial,delivery};}