export const JERMAINE_WILLIAMS_MASTER_TERMS_TITLE="JERMAINE WILLIAMS — MASTER ARTIST, MUSICAL DIRECTION & MUSIC PRODUCTION SERVICES AGREEMENT";
export const JERMAINE_WILLIAMS_MASTER_TERMS_VERSION="2026.1";
export const JERMAINE_WILLIAMS_MASTER_TERMS_2026_1=`JERMAINE WILLIAMS
MASTER ARTIST, MUSICAL DIRECTION & MUSIC PRODUCTION SERVICES AGREEMENT
Texas Master Terms
Version: 2026.1
Effective Date: [______]

This Master Agreement governs Services provided by Jermaine Williams (“Jermaine Williams”) to the client identified in an accepted SOW (“Client”). Each is a “Party”; together, the “Parties.”

1. PURPOSE; CONTRACT STRUCTURE. This Agreement establishes legal, commercial, operational, IP, safety, payment, equipment, production, and risk-allocation terms. Project-specific scope, fees, schedule, deliverables, equipment, and special terms belong in an SOW. Jermaine Williams is the sole provider party unless an executed SOW expressly states otherwise. Its owner, principals, affiliated brands, personnel, contractors, vendors, manufacturers, and production partners are not guarantors or co-obligors merely because they support a Project. No individual personally guarantees performance absent an express written personal guaranty. Jermaine Williams may assign this Agreement to a successor entity that assumes its obligations where permitted by law.

2. DEFINITIONS. “SOW” includes an accepted statement of work, proposal, booking confirmation, order, rental order, or other engagement document incorporating this Agreement. “Services” means only services expressly included in an SOW. “Equipment” means audio, video, broadcast, LED, lighting, networking, communications, computing, power-distribution, cabling, staging-related, backline, or other equipment supplied, rented, procured, integrated, or handled for a Project. “Background IP” includes Jermaine Williams’s pre-existing or independently developed systems, designs, templates, drawings, workflows, programming, show files, code, methods, documentation, and know-how. “Change Order” means an accepted written or authenticated electronic modification. “Client Materials” means materials, information, files, plans, credentials, content, or instructions supplied or directed by Client.

3. SERVICES; EXCLUSIONS. Services may include production management; audio; video; broadcast; LED; lighting; RF; communications; networking; playback; backline; staging coordination; systems architecture; consulting; design; engineering coordination; installation; integration; programming; commissioning; training; rentals; procurement; creative/technical direction; and documentation. Anything not expressly included is excluded, including unlisted labor, equipment, engineering stamps, permits, licenses, structural/electrical work, rehearsals, recording rights, freight, or expenses. Jermaine Williams will perform professionally but does not guarantee attendance, audience response, fundraising, sales, broadcast reach, platform performance, uninterrupted third-party services, or other outcomes outside reasonable control.

4. ORDER OF PRECEDENCE. Conflicts are resolved by: (1) SOW special terms expressly modifying a provision; (2) accepted Addenda; (3) this Agreement; (4) incorporated Riders/specifications/drawings; (5) accepted Change Orders according to their stated effect. Client purchase orders, venue forms, portal terms, emails, texts, or conversations do not modify this Agreement merely by receipt or performance. Modification requires affirmative acceptance by an Authorized Representative.

5. BOOKING; PROJECT COMMENCEMENT. No date, crew, inventory, design capacity, procurement commitment, or production capacity is reserved until required acceptance, payment, and stated booking requirements are complete. Temporary holds expire as stated. Client shall provide materially accurate Project, site, venue, attendance, schedule, power, rigging, network, structural, security, access, and production information. Material omissions or changed conditions may require repricing, redesign, added labor/equipment, schedule changes, or a Change Order.

6. FEES; PAYMENT. Client shall pay the SOW price and milestones. Jermaine Williams may require remaining balances before deployment, delivery, installation, performance, transfer of deliverables, or Equipment release. Past-due amounts may accrue the lesser of the SOW rate or maximum lawful rate plus recoverable collection costs. Except where prohibited, undisputed amounts may not be offset for unrelated claims. Subject to required notice/cure, Jermaine Williams may suspend design, procurement, preparation, crew, delivery, installation, deliverables, or performance for nonpayment without waiving amounts due. Client shall provide reasonable written notice of a good-faith payment dispute before chargeback except where law/network rules provide otherwise; knowingly improper chargebacks are material breach.

7. TAXES; FREIGHT; EXPENSES. Client shall pay legally chargeable transaction taxes and SOW-allocated freight, shipping, delivery, permit, customs, travel, and reimbursable expenses. Jermaine Williams remains responsible for taxes on its own income.

8. PERSONNEL; SIDEMEN; MUSICAL DIRECTION. Jermaine Williams may select and direct musicians, vocalists, arrangers, programmers, engineers, assistants, contractors, and other personnel reasonably needed for the engagement. Unless an SOW expressly makes Client the direct engager, such personnel do not become Client employees merely by participating. As musical director, Jermaine Williams may exercise reasonable professional judgment concerning arrangements, instrumentation, charts, playback, rehearsals, substitutions, musical transitions, keys, tempos, programming, and performance execution consistent with the approved creative brief.

9. ARTIST SERVICES; PERFORMANCE SCOPE. Artist services may include featured bass performance, multi-instrumental performance, musical direction, band leadership, arranging, rehearsal direction, programming, playback preparation, production, recording, editing, and related creative services. Performance length, ensemble, rehearsal allotment, soundcheck, repertoire, wardrobe requirements, guest participation, backline, travel, and production requirements are governed by the SOW/Rider. Client may not materially expand performance duration, ensemble, repertoire, rehearsals, media exploitation, or deliverables without an approved Change Order.

10. CREATIVE AND PROFESSIONAL CONTROL. Client may define objectives, approved brief, brand requirements, and expressly contracted deliverables. Jermaine Williams retains reasonable professional control over artistic and technical means and methods, including performance interpretation, musical execution, production workflow, instrument/gear choices, personnel direction, and creative recommendations. Client feedback does not require work that is unlawful, unsafe, technically unsound, outside scope, or materially inconsistent with the approved artistic engagement.

11. REPERTOIRE; ARRANGEMENTS; CHARTS. Repertoire, custom arrangements, charts, stems, playback files, patches, show files, and rehearsal materials are included only as stated. Unless expressly assigned, Jermaine Williams retains rights in original arrangements, charts, programming, templates, and production materials to the extent he owns them, subject to underlying third-party composition rights. Client receives only the license expressly stated in the SOW.

12. MUSIC PRODUCTION SERVICES. Production may include preproduction, composition assistance, arrangement, instrumentation, programming, recording, editing, vocal/instrument production, sound design, and delivery preparation as stated in the SOW. The SOW shall identify the song/project, expected deliverables, revision rounds, delivery format, schedule, fee structure, and any royalty, point, publishing, master, or credit terms. Services not expressly listed are excluded.

13. REVISIONS; APPROVALS. Included revision rounds, if any, are stated in the SOW. A “revision” means a reasonable modification within the approved creative direction, not a new song, new arrangement, replacement production concept, newly recorded ensemble, material rewrite, or other scope expansion. Client shall consolidate feedback through an authorized representative. Additional revisions or direction changes may require a Change Order.

14. MASTERS; STEMS; MULTITRACKS; SESSION FILES. Delivery of a stereo master or other final deliverable does not automatically include multitracks, stems, DAW sessions, raw recordings, MIDI, presets, sample libraries, templates, alternate takes, production files, source files, or working files. Such materials are delivered or licensed only when expressly stated. Third-party licensed materials may be subject to additional restrictions.

15. COMPOSITIONS; PUBLISHING; SONGWRITING. No music-production fee, performance fee, or creative-services fee by itself transfers Jermaine Williams’s songwriter, composer, arranger, or publishing interest. Songwriting splits and publishing interests shall be documented separately or in the SOW when applicable. No Party may knowingly register or claim another contributor’s share contrary to the parties’ documented split. Where splits remain unresolved, the Parties shall cooperate in good faith to document actual contributions before conflicting registrations.

16. MASTER OWNERSHIP; PRODUCER RIGHTS. Ownership of sound recordings created under an engagement must be expressly stated in the SOW. If Client is to own a commissioned master, transfer is conditioned upon full payment and remains subject to retained composition/publishing rights, third-party rights, and any expressly reserved producer royalty/points, credit, portfolio, or neighboring-right interests. If no ownership transfer is expressly stated, no master copyright assignment is implied merely by payment.

17. WORK MADE FOR HIRE; ASSIGNMENTS. No deliverable is a “work made for hire,” and no copyright is assigned, unless an executed writing expressly identifies the applicable work and states the intended work-for-hire/assignment treatment. To the extent a valid work-for-hire designation fails legally, any fallback assignment must be expressly stated. Background IP, general know-how, templates, methods, performance style, preexisting materials, and rights not expressly conveyed remain excluded.

18. PRODUCER POINTS; ROYALTIES; ACCOUNTING. If an SOW grants producer points, royalties, backend participation, or other contingent compensation, the SOW shall define the base, rate, accounting periods, deductions if any, statements, payment timing, audit rights if any, and treatment of licenses, advances, settlements, bundles, and nontraditional exploitation. No royalty obligation is created merely by describing Jermaine Williams as producer unless the SOW expressly provides one.

19. CREDITS. Required billing and credits shall be stated in the SOW. Client shall use commercially reasonable efforts to provide agreed credit in metadata, liner notes, DSP submissions, video descriptions, publicity, or other agreed placements within Client’s control. Inadvertent isolated credit omission is not a material breach if corrected prospectively within a reasonable time after notice where correction is commercially practicable.

20. NAME; IMAGE; LIKENESS; VOICE. Client receives no unrestricted right to Jermaine Williams’s name, image, likeness, voice, signature, biography, trademarks, or persona. Authorized promotional use is limited to truthful promotion of the contracted engagement and any expressly approved exploitation. Merchandising, product endorsement, political use, paid advertising beyond agreed event/project promotion, digital replicas, synthetic voice/image, or use implying unrelated endorsement requires separate written permission.

21. AI; DIGITAL REPLICAS; SYNTHETIC PERFORMANCE. Client shall not use recordings, images, stems, isolated tracks, session files, biometric characteristics, voice, playing style, motion, or other protected materials to train/fine-tune generative systems, create a digital replica, synthesize new performances, clone voice/instrumental identity, or generate derivative commercial performances purporting to be Jermaine Williams without express written authorization defining scope, duration, media, compensation, and controls. Ordinary authorized technical processing for editing, restoration, noise reduction, accessibility, search, security, or distribution is not prohibited unless used to create unauthorized synthetic exploitation.

22. INTELLECTUAL PROPERTY; BACKGROUND IP. Each Party retains preexisting IP. Jermaine Williams retains Background IP including production methods, templates, arrangements, patches, sounds to the extent owned, show files, programming methods, workflows, techniques, documentation, musical concepts not specifically assigned, and know-how. Client retains Client Materials and represents it has rights necessary for directed use. Ownership/license of commissioned deliverables is only as expressly stated.

23. RECORDING; BROADCAST; STREAMING; CAPTURE. A live-performance booking does not automatically authorize commercial audio/video recording, livestreaming, broadcast, synchronization, paid distribution, archival exploitation, isolated-track capture, or creation of commercial releases. Permitted capture and exploitation must be stated in the SOW or separately approved. Incidental audience/venue capture outside Client’s reasonable control is treated differently from Client-directed commercial exploitation. Client remains responsible for third-party music, union, venue, platform, and content clearances allocated to it.

24. SCHEDULE; DELAYS; OVERTIME. SOW access, load-in, installation, rehearsal, soundcheck, doors, show, strike, pickup, commissioning, and curfew times are material. Client/Venue-caused delay does not automatically extend end time or waive overtime, labor, standby, remobilization, freight, or resulting charges. Jermaine Williams will reasonably attempt accommodation subject to personnel/equipment/transport/venue constraints. Overtime requires authorization and applicable fees/availability.

25. CHANGE ORDERS. Material scope changes require written/electronic approval and may affect price, schedule, equipment, design, labor, engineering, permits, freight, procurement, travel, testing, and availability. Authenticated WGOS approval may satisfy this requirement. Emergency field conditions may require immediate protective action; material scope/cost effects shall be documented as practicable. One accommodation creates no ongoing uncompensated obligation.

26. CLIENT CANCELLATION. Cancellation must be written. The SOW states any cancellation schedule. In addition to amounts properly due under an enforceable schedule, Client remains responsible to the extent permitted by law for performed Services, completed design/preparation, authorized nonrecoverable travel/freight, crew commitments, custom fabrication/configuration, special-order procurement, rentals, subcontractor commitments, restocking/cancellation charges, and other authorized nonrecoverable obligations, without duplicate recovery. Where identified as liquidated damages, amounts are intended as a reasonable forecast of difficult-to-determine anticipated losses including reserved capacity/displaced opportunities, not a penalty, only to the extent enforceable.

27. POSTPONEMENT. Postponement requires written approval. Jermaine Williams will reasonably consider replacement dates but does not guarantee personnel, inventory, vendor, venue, or Equipment availability. Client remains responsible for additional/nonrecoverable postponement costs. An unaccommodated postponement may be treated under cancellation terms unless otherwise agreed.

28. FORCE MAJEURE. Neither Party is liable for failure/delay caused by circumstances beyond reasonable control materially preventing, making unlawful, or making unsafe performance, including natural disaster, severe weather, fire, flood, epidemic restrictions, war, terrorism, civil disorder, governmental order, transportation disruption, widespread utility/network failure, venue destruction, non-caused labor disruption, supply embargo, or comparable events. The affected Party shall provide practicable notice and commercially reasonable mitigation. Parties shall reasonably explore rescheduling. Jermaine Williams need not absorb completed work or authorized nonrecoverable commitments. Reconciliation considers performed Services, transferable/recoverable commitments, SOW terms, and law without windfall/duplicate recovery.

29. JERMAINE WILLIAMS CANCELLATION. If Jermaine Williams cancels for reasons within reasonable control without agreed substitute, cure, or reschedule, it shall refund amounts paid for unperformed Services subject to remedies that cannot lawfully be limited. Jermaine Williams receives no Client cancellation damages when Jermaine Williams wrongfully cancels.

30. CLIENT DEFAULT. Material default may include nonpayment, material misrepresentation, denied access, failure to provide agreed site/power/structural/rigging/production/safety/security/infrastructure, unlawful instructions, unauthorized Equipment use, expanded scope without agreement, dangerous/abusive conduct, interference with safe operations, or other material breach. Where reasonably curable, Client receives a reasonable opportunity considering Project timing. If uncured, Jermaine Williams may suspend/terminate Services, secure/de-energize Equipment where reasonably necessary, recover its property as permitted by law, and pursue remedies.

31. REPRESENTATIONS; AUTHORITY. Each Party represents authority to enter the engagement, reasonably sufficient authority of its accepting representative, no knowing violation of another binding agreement, and compliance with laws materially applicable to its own obligations. Client represents authority to grant agreed access to sites, systems, Client Materials, credentials, and equipment.

32. INDEPENDENT CONTRACTOR. Jermaine Williams is an independent contractor. Nothing creates employment, agency, fiduciary, franchise, joint venture, or partnership with Client. Jermaine Williams controls means/methods subject to agreed requirements, law, and safety.

33. THIRD-PARTY PROVIDERS. Jermaine Williams may engage subcontractors, technicians, vendors, manufacturers, rental houses, carriers, and production partners. Unless Client separately contracts directly with a provider, Jermaine Williams remains responsible for its contractual obligations subject to this Agreement. Jermaine Williams is not responsible for independent providers separately selected/contracted by Client/Venue.

34. INDEMNIFICATION. To the extent permitted by law, Client shall defend, indemnify, and hold harmless Jermaine Williams and its owners/principals/personnel/representatives from third-party claims, damages, liabilities, judgments, and reasonable defense costs to the extent arising from Client negligence/willful misconduct, material breach, infringing Client Materials/instructions, site/venue/structural/electrical/network/security/crowd/infrastructure conditions allocated to Client, unauthorized Equipment use/modification, or Client-controlled contractors/vendors, except to the extent caused by an indemnified party’s own responsibility that law does not permit shifted. Jermaine Williams shall similarly defend/indemnify Client for third-party claims to the extent arising from Jermaine Williams negligence/willful misconduct, material breach, or infringing Jermaine Williams-provided materials, except to the extent caused by Client/responsible persons. Prompt notice, qualified defense control, reasonable cooperation, and consent to settlements imposing admission/nonmonetary obligation/unreimbursed liability apply.

35. LIMITATION OF LIABILITY. To the maximum extent permitted by law, neither Party is liable to the other for indirect, incidental, special, exemplary, punitive, or consequential damages, including speculative lost profits, donations, ticket sales, audience, reputation, or opportunities. Jermaine Williams aggregate contractual liability arising from a particular SOW shall not exceed fees paid/payable under that SOW. Limitations do not apply where law prohibits and may have SOW carve-outs. No duplicate recovery.

36. INSURANCE. Insurance, certificates, waivers, and additional-insured requirements shall be stated in the SOW/Rider. Insurance availability does not enlarge contractual liability.

37. DAMAGE; LOSS; THEFT. Each Party is responsible to the extent permitted by law for physical loss/damage legally attributable to it. Client is responsible for Jermaine Williams-controlled Equipment loss/damage/theft legally attributable to Client, its personnel/vendors/guests, or conditions under Client responsibility. Ordinary wear, inherent defect, Jermaine Williams-caused damage, and ordinary equipment failure remain Jermaine Williams responsibility.

38. WARRANTIES; DISCLAIMER. Jermaine Williams warrants professional Services and express SOW warranties. Except express warranties and nonwaivable rights, Jermaine Williams makes no implied guarantee concerning third-party products, uninterrupted operation, compatibility with undisclosed systems, future manufacturer/platform support, or fitness for undisclosed uses.

39. CLIENT MODIFICATIONS. Jermaine Williams is not responsible for failures caused by unauthorized modification, relocation, reprogramming, rewiring, firmware/credential changes, misuse, improper maintenance, third-party repair, incompatible additions, or operation contrary to documentation after delivery/commissioning. Diagnosis/restoration/recommissioning caused by such intervention may be charged.

40. DATA; FILES; BACKUPS. Unless expressly included, Client is responsible for archival backups of Client-owned media, recordings, configurations, credentials, and data after delivery. Jermaine Williams may maintain working/project records for operational, legal, backup, and portfolio purposes subject to confidentiality/rights. No indefinite retention obligation exists unless stated.

41. PUBLICITY; PORTFOLIO. No engagement grants endorsement rights. Each Party retains names/marks. Jermaine Williams may truthfully identify Client/Project in professional history and use nonconfidential documentation of its work for portfolio/marketing unless SOW/confidentiality prohibits. Uses implying broader endorsement/sponsorship require approval.

42. DISPUTE ESCALATION. Authorized Representatives shall first attempt good-faith business resolution. If unresolved, either Party may request confidential mediation in Harris County, Texas. Unless urgent relief is reasonably necessary, mediation precedes final arbitration.

43. BINDING ARBITRATION. Except expressly excluded matters, unresolved disputes arising from this Agreement/SOW shall be resolved by binding arbitration administered by the American Arbitration Association under applicable commercial rules unless otherwise agreed. The Federal Arbitration Act governs the arbitration agreement where applicable; Texas substantive law governs merits except where federal law controls. Seat: Harris County, Texas. One neutral arbitrator unless rules/agreement require otherwise. Discovery shall be proportional. The arbitrator may award lawful Agreement remedies but not rewrite the substantive bargain beyond authority. Nonpublic proceedings/materials remain confidential to the extent lawful subject to necessary disclosures. Either Party may seek temporary/preliminary/injunctive/equitable court relief reasonably necessary to protect IP, confidential information, safety, property, payment security, Equipment, or status quo pending arbitration without waiver. A reasoned written award may be requested as permitted; judgment may be entered by a court with jurisdiction.

44. ATTORNEYS’ FEES; COSTS. Fees, arbitration expenses, court costs, and dispute-related costs may be awarded to the extent authorized by this Agreement, applicable law, or rules.

45. GOVERNING LAW. Texas substantive law governs without regard to conflicts principles except where applicable federal law controls.

46. NOTICES. Formal legal notices go to SOW-designated or later written notice destinations. Operational communications may occur through WGOS, email, text, or production systems. Routine operational communication is not automatically formal legal notice where formal notice is required.

47. ELECTRONIC TRANSACTIONS; WGOS RECORDS. Parties consent to electronic transactions to the extent permitted by law. Electronic signatures, authenticated approvals, timestamps, payment records, identity evidence, audit trails, document versions, delivery records, Equipment custody records, and other reliable electronic evidence may establish execution, acceptance, attribution, modification, delivery, custody, or performance. Jermaine Williams may maintain authoritative records through WGOS or successor platform. Electronic acceptance does not diminish legal requirements.

48. ASSIGNMENT; SUCCESSORS. Client may not assign in a manner materially changing Project, counterparty risk, site, conditions, or Jermaine Williams obligations without written consent. Jermaine Williams may assign to a successor in reorganization, incorporation, conversion, merger, sale, or transfer of substantially all relevant operations if the successor assumes obligations.

49. THIRD-PARTY BENEFICIARIES; NONEXCLUSIVITY. Except persons expressly protected by indemnity/liability provisions, no third-party rights are created. Unless stated, neither Party grants exclusivity. Jermaine Williams may serve other clients, including competitors, subject to confidentiality.

50. NO WAIVER; SEVERABILITY; REFORMATION. Delay/failure enforcing a right is not waiver. A waiver is matter-specific unless stated. Invalid/unenforceable provisions do not defeat remaining terms. Where lawful, an unenforceable provision shall be reformed only minimally to preserve lawful intent.

51. SURVIVAL; ENTIRE AGREEMENT; AMENDMENTS. Payment, Equipment/property rights, IP, confidentiality, media/data rights, indemnity, liability limits, dispute resolution, and accrued rights survive as appropriate. This Agreement with SOW, accepted Addenda, incorporated Riders/specifications/drawings, and Change Orders is the entire engagement agreement and supersedes prior/contemporaneous representations on the subject, except where law provides otherwise. Amendments require Authorized Representatives in writing/authenticated electronic process; operational personnel cannot modify terms merely through conversation.

52. COUNTERPARTS; INTERPRETATION; ACCEPTANCE. Documents may be executed in counterparts/electronically. Headings are convenience only. “Include/including” mean without limitation unless context requires. Singular includes plural where appropriate. No presumption against drafter applies merely because one Party prepared the document to the extent permitted by law. Executing an incorporating SOW acknowledges receipt/reasonable access and agreement to these terms. Separate execution may also be used.

OPTIONAL SIGNATURE PAGE
CLIENT
Legal Name: __________________________________
Authorized Representative: _____________________
Title: _______________________________________
Signature: ___________________________________
Date: _______________________________________

JERMAINE WILLIAMS
By its Authorized Representative:
Name: _______________________________________
Title/Capacity: _______________________________
Signature: ___________________________________
Date: _______________________________________
`;
