export const SOUND_LEGACY_INSTITUTE_MASTER_TERMS_TITLE="SOUND LEGACY INSTITUTE — MASTER STUDENT ENROLLMENT, MUSIC EDUCATION & COMMUNITY PROGRAM AGREEMENT";
export const SOUND_LEGACY_INSTITUTE_MASTER_TERMS_VERSION="2026.1";
export const SOUND_LEGACY_INSTITUTE_MASTER_TERMS_2026_1=`SOUND LEGACY INSTITUTE
MASTER STUDENT ENROLLMENT, MUSIC EDUCATION & COMMUNITY PROGRAM AGREEMENT
Texas Master Terms
Version: 2026.1
Effective Date: [______]

This Master Agreement governs enrollment in and participation in educational, artistic, performance, community, and related programs offered by Sound Legacy Institute (“SLI”). For a minor Student, “Parent” means the parent or legal guardian accepting this Agreement. “Student” means the enrolled learner. The accepting adult and, where applicable, an adult Student are the “Responsible Party.” Program-specific enrollment confirmations, tuition schedules, handbooks, policies, consent forms, and addenda incorporated into this Agreement are collectively the “Enrollment Documents.”

1. PURPOSE; SCHOOL MISSION; CONTRACT STRUCTURE. SLI is a music-education institution being developed to provide high-quality instruction, artistic development, mentorship, performance opportunities, and community service, initially including programs serving children and youth and later potentially including adult, virtual, recording, production-arts, and other creative curricula. This Agreement establishes the baseline relationship among SLI, Student, and Responsible Party. Program-specific course, schedule, tuition, faculty, instrument, performance, technology, and special terms belong in the Enrollment Documents. SLI’s charitable or nonprofit status, when obtained, does not make tuition, fees, policies, scholarships, donations, or services automatically tax-deductible or free.

2. DEFINITIONS. “Program” means an enrolled lesson, class, ensemble, workshop, camp, clinic, lab, performance program, virtual course, community program, or other educational offering. “Faculty” includes instructors, teaching artists, coaches, accompanists, clinicians, and authorized substitutes. “School Property” includes instruments, music, equipment, technology, facilities, credentials, recordings, and materials owned, licensed, or controlled by SLI. “Student Work” means a Student-created composition, arrangement, recording, performance, project, or other original work. “Virtual Services” means instruction or programming delivered through internet-connected technology. “Authorized Pickup Person” means a person whom the Responsible Party has authorized under SLI procedures to receive a minor Student.

3. ENROLLMENT; ELIGIBILITY; ACCURATE INFORMATION. Enrollment is effective only after SLI accepts the Student and required Enrollment Documents, tuition/deposit, emergency information, and consents are completed. Responsible Party shall provide materially accurate age, contact, emergency, allergy, accessibility, custody/release, and other information reasonably necessary to serve the Student safely. SLI may establish age, audition, prerequisite, skill, capacity, behavioral, equipment, or other neutral Program requirements.

4. PARENT OR GUARDIAN AUTHORITY. A person enrolling a minor represents that the person has legal authority to do so and to provide the permissions given in the Enrollment Documents. Responsible Party shall promptly disclose any court order, custody restriction, protective order, pickup limitation, or other legal restriction material to SLI’s care or release of the Student and provide documentation reasonably requested. SLI is not required to adjudicate family disputes and may follow the latest reliable documentation in its records unless law requires otherwise.

5. TUITION; FEES; PAYMENT. Tuition, registration, materials, instrument, lab, performance, technology, late, and other authorized fees are stated in the Enrollment Documents. Payment is due according to the stated schedule. SLI may use installment plans or recurring billing with required authorization. Past-due balances may result in suspension of nonessential participation or reenrollment subject to applicable law and any written financial-aid arrangement. SLI will not impose undisclosed fees.

6. SCHOLARSHIPS; FINANCIAL AID; DONOR-SUPPORTED ACCESS. Scholarships, tuition assistance, sponsored seats, and grants are subject to available funds, eligibility criteria, donor restrictions that SLI lawfully accepts, and written award terms. Awards may be changed prospectively when funding or eligibility changes, subject to commitments already made. Donors and sponsors receive no right to control a Student, obtain private Student information, or use a Student’s identity merely by funding a Program.

7. CANCELLATION; WITHDRAWAL; REFUNDS. Responsible Party may withdraw according to the applicable Enrollment Documents. Registration fees, deposits, prepaid tuition, missed lessons, camps, intensives, and special commitments are refundable or nonrefundable only as stated and as permitted by law. SLI may retain amounts reasonably attributable to delivered instruction and authorized nonrecoverable commitments. SLI will not impose a penalty prohibited by law.

8. SCHOOL CANCELLATION; PROGRAM CHANGES. SLI may cancel, combine, relocate, reschedule, move online, change reasonable Program details, or substitute qualified Faculty when necessary because of enrollment, Faculty availability, facility conditions, safety, weather, public-health conditions, or other legitimate educational or operational reasons. If SLI permanently cancels a paid Program without reasonable substitute or credit, SLI will refund the allocable prepaid amount for undelivered services unless law or an Enrollment Document provides a greater remedy.

9. ATTENDANCE; ABSENCES; MAKEUPS. Regular attendance and punctuality support educational progress. Makeups, credits, rescheduling, and Faculty-absence procedures are governed by the applicable Program policy. Student absence does not automatically create a refund or makeup right. SLI will reasonably distinguish Student absences from SLI cancellations and may adopt reasonable illness and communicable-disease attendance practices.

10. CURRICULUM; EDUCATIONAL JUDGMENT. SLI controls curriculum, instructional sequence, repertoire, pedagogy, ensemble placement, assessment methods, performance readiness, and other educational means, while considering Student goals and age-appropriate development. SLI may update curriculum as its programs evolve. Enrollment does not guarantee advancement, audition results, admission to another institution, professional employment, earnings, awards, or a particular artistic outcome.

11. PLACEMENT; AUDITIONS; ADVANCEMENT. Placement, ensemble assignment, chair/part assignment, advancement, recital eligibility, and similar decisions may consider skill, preparation, attendance, instrumentation, balance, maturity, safety, and educational objectives. Auditions and evaluations are educational tools and do not promise a particular role, ranking, solo, scholarship, or outcome.

12. FACULTY; SUBSTITUTES; GUEST ARTISTS. SLI may select Faculty and reasonably substitute qualified personnel. No Student is guaranteed a particular instructor unless expressly stated. Guest artists, clinicians, accompanists, and contractors may participate under SLI authorization. SLI will establish screening, supervision, conduct, and safeguarding practices appropriate to roles and applicable law.

13. CHILD SAFEGUARDING. SLI will maintain child-safeguarding practices reasonably appropriate to its programs and applicable law, including boundaries for adult-minor interactions, supervision, reporting, and response to safety concerns. Faculty, staff, volunteers, Students, and families shall comply with applicable safeguarding policies. Nothing in this Agreement limits a legal duty to report suspected abuse, neglect, exploitation, or other conduct that must be reported.

14. BACKGROUND SCREENING; VOLUNTEERS. SLI may require legally permissible background screening, references, training, acknowledgments, or other vetting for employees, contractors, or volunteers whose roles warrant it. Screening is one risk-management measure and is not a guarantee that misconduct cannot occur. Volunteers act only within authorized roles and do not obtain unrestricted access to Students, records, facilities, or systems.

15. STUDENT CONDUCT; RESPECTFUL LEARNING ENVIRONMENT. Students shall follow reasonable rules concerning safety, attendance, preparation, property, respectful conduct, academic/artistic integrity, technology, and disruption. Bullying, harassment, threats, violence, sexual misconduct, discriminatory harassment, theft, intentional property damage, and dangerous behavior are prohibited. Age, disability, developmental context, and the seriousness and recurrence of conduct may be considered in responsive measures.

16. PARENT; FAMILY; VISITOR CONDUCT. Parents, guardians, family members, and visitors shall interact respectfully with Students, Faculty, staff, and other families and follow facility, security, privacy, and safeguarding rules. Threatening, abusive, harassing, dangerous, or materially disruptive conduct may result in restricted access or other proportionate action without automatically penalizing the Student where a safe alternative is reasonably available.

17. DISCIPLINE; SUSPENSION; DISMISSAL. SLI may use age-appropriate corrective measures including conference, warning, behavior plan, reassignment, temporary suspension, or dismissal for material or repeated violations. Immediate protective action may be taken for credible safety threats or serious misconduct. Where practicable and appropriate, SLI will communicate material concerns to the Responsible Party and provide a reasonable opportunity to respond.

18. NONDISCRIMINATION; ACCESS. SLI intends to serve its community without unlawful discrimination and will comply with nondiscrimination obligations applicable to its operations, programs, funding, and facilities. SLI may maintain lawful mission-based, age-based, skill-based, program-capacity, or pedagogical criteria. Requests for disability-related access or modification should be raised promptly so SLI can engage in the process required by applicable law.

19. DISABILITY ACCOMMODATIONS; INDIVIDUAL NEEDS. Responsible Party should disclose accommodations or material support needs reasonably necessary for safe and meaningful participation. SLI will consider reasonable accommodations as required by applicable law while preserving essential Program requirements and safety. SLI is not a medical, therapeutic, special-education, or clinical provider unless a particular service is expressly represented as such.

20. HEALTH; ALLERGIES; MEDICATION; MEDICAL INFORMATION. Responsible Party shall provide material health, allergy, medication, mobility, sensory, or emergency information requested for safe participation and update it when necessary. SLI will use such information for legitimate educational, safety, accessibility, and emergency purposes and protect it consistent with applicable privacy obligations. Medication administration, if offered, is governed by separate policy and authorization.

21. EMERGENCIES; FIRST AID; MEDICAL CARE. In an apparent emergency, SLI may provide reasonable first aid, contact emergency services, contact listed emergency persons, and take other reasonable protective action. Responsible Party authorizes emergency evaluation or treatment when legally permissible and reasonably necessary if timely contact cannot be made, without making SLI the guarantor of medical outcomes. Financial responsibility for third-party medical services follows applicable law and insurance arrangements.

22. ARRIVAL; DISMISSAL; PICKUP; RELEASE OF MINORS. Responsible Party shall follow published arrival, dismissal, sign-in/out, transportation, and pickup procedures. SLI may release a minor only as permitted by its records, policies, and applicable law. Responsible Party shall timely retrieve the Student and keep Authorized Pickup Persons current. SLI may require identification and may refuse release when authorization is materially uncertain while seeking clarification or appropriate assistance.

23. TRANSPORTATION; FIELD TRIPS; OFF-SITE ACTIVITIES. Transportation is not included unless expressly stated. Field trips, festivals, competitions, performances, tours, and off-site activities may require separate permission, transportation terms, chaperone rules, medical information, costs, and risk disclosures. Responsible Party remains responsible for transportation it arranges independently.

24. FACILITIES; SECURITY; ACCESS. Students and visitors shall use only authorized areas and follow access, security, parking, emergency, and facility rules. SLI may use leased, partner, school, church, studio, performance, or community facilities and is not the owner or operator of every site. Site-specific rules may supplement this Agreement. SLI will not knowingly require participation in conditions it reasonably determines present an unacceptable safety risk.

25. INSTRUMENTS; SCHOOL PROPERTY; PERSONAL PROPERTY. School Property remains its owner’s property. Borrowed or rented instruments and equipment are governed by applicable checkout/rental terms. Responsible Party is liable to the extent permitted by law for loss or damage legally attributable to Student or Responsible Party beyond ordinary wear. Students should identify and safeguard personal property; SLI is not an insurer of personal instruments or belongings.

26. PRACTICE; HEARING; PHYSICAL WELLNESS. Music study can involve repetitive motion, amplified sound, performance stress, and physical demands. Students should follow age-appropriate Faculty guidance, use hearing protection where appropriate, take reasonable breaks, and report pain, dizziness, hearing symptoms, or unsafe conditions. SLI may modify or pause an activity for safety. SLI does not provide medical diagnosis or treatment.

27. VIRTUAL INSTRUCTION. Virtual Services may use approved video, learning-management, messaging, file-sharing, or collaboration platforms. Responsible Party shall provide required connectivity, compatible equipment, and an appropriate learning environment unless otherwise stated. SLI may establish rules for account identity, camera use, recording, chat, direct messaging, parent presence for younger Students, and appropriate backgrounds. Third-party platform outages may require rescheduling or alternate delivery.

28. ONLINE SAFETY; CHILDREN’S PRIVACY. SLI will use reasonable age-appropriate online-safety practices and comply with privacy and parental-consent requirements applicable to its collection and use of children’s information, including laws that apply to particular online services or funding relationships. Responsible Party shall not create unauthorized recordings, screenshots, accounts, or disclosures involving other Students. SLI may restrict platforms or features that do not meet its safety or privacy requirements.

29. STUDENT RECORDS; PRIVACY. SLI may maintain enrollment, attendance, billing, assessment, communication, emergency, safeguarding, performance, scholarship, and other legitimate educational/operational records. Access and disclosure will be governed by applicable law, SLI policy, consent, safety needs, and legitimate operations. SLI will not represent that a particular federal student-record law applies unless its legal prerequisites are met; where such law applies, SLI will comply.

30. COMMUNICATIONS WITH MINORS. SLI may establish approved channels and boundaries for Faculty communications with minor Students, including copying parents/guardians, using institutional accounts, group channels, learning platforms, or age-appropriate exceptions. Faculty and Students shall not use communications to evade safeguarding rules. Responsible Party consents to ordinary educational communications conducted under SLI policy.

31. PHOTOGRAPHY; AUDIO; VIDEO; MEDIA CONSENT. Enrollment alone does not grant SLI unrestricted commercial rights to a Student’s identity. SLI may capture reasonable internal educational, security, archival, assessment, or event documentation as permitted by law and disclosed policy. Public promotional use of an identifiable minor’s name, image, voice, or performance will follow the applicable parent/guardian consent process. A Student will not be denied ordinary educational access merely because optional promotional consent is declined, except where media participation is an inherent disclosed element of a particular Program.

32. PERFORMANCES; RECITALS; CONCERTS. Programs may include recitals, concerts, showcases, juries, festivals, community performances, or public events. Participation may depend on readiness, attendance, instrumentation, capacity, safety, and Program requirements. Performance opportunities, solos, roles, repertoire, venue, audience size, recording, or publicity are not guaranteed unless expressly stated.

33. MUSIC LICENSING; THIRD-PARTY WORKS. Compositions, recordings, scores, method books, software, samples, backing tracks, and other third-party materials remain subject to applicable rights and licenses. Enrollment does not grant Students a right to reproduce, distribute, upload, sell, or commercially exploit third-party materials. SLI may require lawful copies or licenses and may restrict unauthorized duplication.

34. STUDENT WORK; OWNERSHIP. Students retain ownership of original Student Work to the extent provided by law, subject to third-party rights and any separate collaboration, commission, recording, publishing, or production agreement. Ordinary enrollment does not transfer a Student’s songwriting, composition, master, publishing, performance, or publicity rights to SLI. SLI may receive a limited educational license to review, perform, display, or store Student Work as reasonably necessary for the Program.

35. COLLABORATIVE WORK; SPLITS; CREDITS. Collaborative compositions, recordings, arrangements, productions, and projects may create shared rights. SLI may teach documentation practices and facilitate split discussions but does not guarantee agreement among collaborators. Students and Responsible Parties should not knowingly submit false ownership claims. Commercial exploitation may require a separate written agreement among rights holders.

36. RECORDING & PRODUCTION ARTS CURRICULUM. SLI may add recording, engineering, beat-making, composition, arranging, live production, broadcast, music technology, and production-arts Programs. Labs may involve microphones, headphones, instruments, computers, interfaces, consoles, software, networks, cameras, lighting, and other equipment. Students shall follow lab safety, credential, file-management, copyright, and equipment-use rules. Educational lab access does not grant ownership of SLI facilities, software, templates, samples, or systems.

37. RECORDINGS; MASTERS; SESSION FILES. Classroom or Student-project recordings are educational unless a separate document states commercial terms. Ownership of masters, multitracks, stems, session files, producer interests, performer permissions, samples, and distribution rights for a commercial or externally released project must be stated separately. SLI does not acquire such rights merely by providing instruction, facilities, or supervision.

38. INTELLECTUAL PROPERTY; SLI MATERIALS. SLI retains its curriculum, lesson frameworks, assessments, templates, instructional recordings, branding, methods, software/configurations, internal documentation, and other preexisting or independently developed intellectual property. Enrollment grants only the limited personal educational use reasonably necessary for the Student. Students may not commercially redistribute SLI curriculum or credentials without permission.

39. AI; DIGITAL REPLICAS; SYNTHETIC MEDIA. Neither enrollment nor participation grants SLI, Student, Responsible Party, Faculty, or another participant unrestricted rights to train or fine-tune AI on another person’s protected nonpublic recordings, voice, likeness, biometric information, isolated performances, or Student Work; create unauthorized digital replicas; or falsely imply endorsement. Educational AI use may be governed by course policy and applicable consent, privacy, copyright, and academic-integrity requirements.

40. TECHNOLOGY; ACCOUNTS; CYBERSECURITY. Students shall protect credentials, use systems only as authorized, and not bypass security, access another user’s account, introduce malicious code, unlawfully copy data, or disrupt networks. No system is guaranteed failure-proof. SLI may suspend technology access reasonably necessary to investigate or contain a security concern and may require password or account changes.

41. COMMUNITY PROGRAMS; PARTNERSHIPS. SLI may provide school partnerships, outreach, workshops, scholarships, community ensembles, donor-funded programs, and services at partner locations. Partner organizations remain responsible for obligations expressly allocated to them. A partnership does not automatically make SLI responsible for another organization’s employees, facilities, transportation, data, or acts, nor does it give a partner control over individual Students beyond agreed roles.

42. CHARITABLE; NONPROFIT OPERATIONS. SLI intends to serve educational and community purposes and may operate through or transition into a tax-exempt nonprofit entity. No private person receives a right to charitable assets, governance authority, donor funds, or restricted grants merely through enrollment or contracting. Donations, restricted gifts, scholarships, conflicts of interest, and charitable resources will be administered under applicable law and governing policies. Tax deductibility of a payment depends on law and circumstances; SLI does not promise a deduction.

43. FUNDRAISING; DONORS; SPONSORS. SLI may fund programs through donations, grants, sponsorships, events, and community partners. Student participation in fundraising will be age-appropriate and subject to applicable policy and consent. SLI will not sell access to Students or private Student records. Sponsor recognition does not permit an endorsement using a Student’s identity without required permission.

44. FORCE MAJEURE; SCHOOL CLOSURES. Neither party is liable for delay or inability to perform caused by circumstances beyond reasonable control, including severe weather, natural disaster, fire, epidemic restrictions, governmental order, facility closure, transportation disruption, widespread utility/network failure, or comparable events. SLI will use reasonable efforts to provide rescheduling, remote instruction, credit, alternate programming, or other fair adjustment appropriate to the affected Program and applicable Enrollment Documents.

45. ASSUMPTION OF ORDINARY PROGRAM RISKS; NO WAIVER OF NONWAIVABLE RIGHTS. Music education and related activities involve ordinary risks such as travel within facilities, instrument handling, amplified sound, stage movement, cables, group activity, and performance. Responsible Party acknowledges ordinary disclosed risks but does not release SLI from liability that cannot lawfully be waived. Nothing in this Agreement is intended to waive a child’s or consumer’s nonwaivable statutory rights.

46. RESPONSIBILITY FOR CONDUCT; INDEMNITY LIMITS. Each adult party is responsible for its own legally attributable acts and breaches. To the extent permitted by law, Responsible Party will be responsible for third-party claims arising from the adult’s own unlawful conduct, material breach, or intentional misuse of School Property. This provision is not intended to require a parent to indemnify SLI for SLI’s own negligence, impose an unlawful waiver on a minor, or shift duties that law makes nondelegable.

47. LIMITATION OF LIABILITY. To the maximum extent permitted by law, SLI is not liable for indirect, incidental, special, exemplary, punitive, or consequential damages arising from educational expectations, lost opportunities, auditions, competitions, employment, or third-party platform failures. Any contractual limitation does not apply where prohibited by law, including liability that cannot lawfully be limited for injury, statutory rights, or legally protected claims. No provision guarantees a particular educational or career result.

48. INSURANCE; INCIDENTS; PROPERTY CLAIMS. SLI may maintain insurance appropriate to its operations and may require event-, facility-, vendor-, or partner-specific insurance where appropriate. Insurance does not enlarge or reduce legal duties. Accidents, injuries, safety concerns, property damage, or significant incidents should be reported promptly so SLI can respond, document, preserve information, and notify appropriate persons or authorities where required.

49. CONFIDENTIALITY; SAFEGUARDING EXCEPTIONS. SLI and Responsible Party shall reasonably protect nonpublic information received through the educational relationship. Confidentiality does not prevent disclosures reasonably necessary for Student safety, mandated reporting, emergency response, legal compliance, insurance, professional consultation, investigation of misconduct, or protection of legal rights. SLI cannot promise secrecy where law or safeguarding duties require action.

50. DISPUTE RESOLUTION; CHILD-SAFETY CARVEOUT. Parties should first attempt good-faith administrative resolution through an appropriate SLI representative. If unresolved, they may use confidential mediation in Harris County, Texas. Any arbitration requirement adopted in Enrollment Documents must comply with applicable law and cannot restrict reports to law enforcement, child-protective authorities, regulators, emergency relief, or rights that cannot lawfully be subjected to mandatory arbitration. SLI may seek legal review before applying dispute procedures to claims involving minors.

51. GOVERNING LAW; NOTICES; ELECTRONIC RECORDS. Texas substantive law governs except where federal or other controlling law applies. Formal notices shall use destinations stated in the Enrollment Documents or later written notice. Parties consent to lawful electronic transactions. WGOS or a successor system may maintain authoritative enrollment, consent, signature, payment, version, audit, and communication records. Electronic acceptance does not eliminate any separate parental-consent, privacy, notarization, or other formality required by law.

52. ASSIGNMENT; SUCCESSOR NONPROFIT ENTITY. Responsible Party may not transfer a Student’s enrollment to another person without SLI approval. SLI may assign this Agreement and related operations to a successor nonprofit corporation, tax-exempt organization, or other lawful successor that assumes applicable obligations, subject to restrictions on charitable assets, restricted funds, Student records, privacy, and other applicable law.

53. THIRD-PARTY BENEFICIARIES; NO AGENCY. Except rights expressly created for a Student or protected person, no third-party beneficiary rights are created. Enrollment does not create employment, partnership, joint venture, fiduciary, or agency status between SLI and Responsible Party. Faculty and contractors have only authority actually granted by SLI.

54. NO WAIVER; SEVERABILITY; REFORMATION. Failure to enforce a provision once is not a continuing waiver. If a provision is invalid or unenforceable, remaining provisions remain effective. A court or arbitrator may reform a provision only to the minimum extent lawful and consistent with the Agreement’s purpose. A provision affecting minors, consumers, education, privacy, or charitable operations will not be expanded beyond what law permits.

55. HANDBOOKS; POLICIES; CHANGES. SLI may adopt and reasonably update academic, safety, safeguarding, technology, attendance, facility, virtual-learning, performance, and operational policies as the school develops. Material changes will be communicated prospectively. A policy update cannot retroactively create a material fee or waive a vested legal right without required agreement.

56. ENTIRE AGREEMENT; AMENDMENTS; SURVIVAL. This Agreement together with applicable Enrollment Documents, accepted addenda, consents, and incorporated policies constitutes the agreement concerning enrollment and supersedes prior representations on the same subject. Material amendments require authorized written or authenticated electronic agreement where required. Payment obligations, Student-record/privacy duties, safeguarding provisions, IP, media permissions, dispute terms, and accrued rights survive as appropriate.

57. ACCEPTANCE; ELECTRONIC SIGNATURES; COUNTERPARTS. Documents may be executed electronically and in counterparts to the extent permitted by law. For a minor Student, acceptance must be made by an adult with authority to enroll the Student. By accepting, Responsible Party confirms reasonable access to these terms and applicable Enrollment Documents and agrees to keep required information current. SLI may require separate signatures or consents for media, field trips, medical matters, virtual platforms, commercial recordings, or other activities where separate authorization is appropriate.

ENROLLMENT / SIGNATURE PAGE
STUDENT
Student Name: __________________________________
Date of Birth: __________________________________
Program: ______________________________________

PARENT / LEGAL GUARDIAN OR ADULT STUDENT
Legal Name: ___________________________________
Relationship to Minor (if applicable): _____________
Email / Phone: __________________________________
Signature: _____________________________________
Date: _________________________________________

SOUND LEGACY INSTITUTE
Authorized Representative: ______________________
Title/Capacity: _________________________________
Signature: _____________________________________
Date: _________________________________________
`;
