import "server-only";
import {db} from "./db";

function countMap(data:Record<string,unknown[]>){
 return Object.fromEntries(Object.entries(data).map(([key,value])=>[key,Array.isArray(value)?value.length:0]));
}

export async function buildSystemExport(){
 const sql=db();
 const [
  brands,appUsers,brandMemberships,brandGovernance,brandExperienceProfiles,brandDeliveryProfiles,brandPaymentProfiles,
  legalEntityVersions,agreementPartyTransitions,integrations,integrationLinks,externalObjectMappings,
  organizations,organizationBrands,contacts,contactBrands,crossBrandReferrals,
  opportunities,proposals,proposalSections,proposalLineItems,acceptedSnapshots,proposalAccessTokens,
  agreementTerms,agreements,contractingProfiles,contractingSigners,signatureEnvelopes,
  payments,refundEvents,invoices,
  projects,tasks,taskComments,taskDependencies,recurringTaskRules,recurringTaskRuns,
  calendarEvents,communicationThreads,communicationMessages,
  equipmentAssets,crewProfiles,projectCrewAssignments,projectEquipmentAssignments,
  productionEvents,productionDepartments,productionRequirements,runOfShowItems,advancingCheckpoints,
  approvalRequests,documentTemplates,documentVersions,
  automationRules,workflowDefinitions,workflowRuns,outboxEvents,deadLetterEvents,notificationEvents,
  aiActionExecutions,idempotencyKeys,providerEvents,systemHealthEvents,
  customFieldDefinitions,customFieldValues,tags,entityTags,savedViews,
  dataGovernancePolicies,dataJobs,auditEvents,
  clientPortalAccess
 ]=await Promise.all([
  sql`SELECT * FROM wgos.brands ORDER BY id`,
  sql`SELECT auth_user_id,email,display_name,role,active,created_at,updated_at FROM wgos.app_users ORDER BY email`,
  sql`SELECT * FROM wgos.brand_memberships ORDER BY brand_id,auth_user_id`,
  sql`SELECT * FROM wgos.brand_governance ORDER BY brand_id`,
  sql`SELECT * FROM wgos.brand_experience_profiles ORDER BY brand_id`,
  sql`SELECT * FROM wgos.brand_delivery_profiles ORDER BY brand_id`,
  sql`SELECT * FROM wgos.brand_payment_profiles ORDER BY brand_id`,
  sql`SELECT * FROM wgos.legal_entity_versions ORDER BY brand_id,effective_from NULLS FIRST,id`,
  sql`SELECT * FROM wgos.agreement_party_transitions ORDER BY created_at,id`,
  sql`SELECT id,brand_id,provider,capability,status,last_verified_at,last_error,metadata,created_at,updated_at FROM wgos.integration_registry ORDER BY provider,capability,brand_id NULLS FIRST`,
  sql`SELECT * FROM wgos.integration_links ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.external_object_mappings ORDER BY provider,external_id,id`,
  sql`SELECT * FROM wgos.organizations ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.organization_brands ORDER BY organization_id,brand_id`,
  sql`SELECT * FROM wgos.contacts ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.contact_brands ORDER BY contact_id,brand_id`,
  sql`SELECT * FROM wgos.cross_brand_referrals ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.opportunities ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.proposals ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.proposal_sections ORDER BY proposal_id,position,id`,
  sql`SELECT * FROM wgos.proposal_line_items ORDER BY proposal_id,position,id`,
  sql`SELECT * FROM wgos.accepted_snapshots ORDER BY accepted_at,id`,
  sql`SELECT id,proposal_id,proposal_version,purpose,created_at,revoked_at FROM wgos.proposal_access_tokens ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.agreement_terms ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.agreements ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.contracting_profiles ORDER BY brand_id`,
  sql`SELECT * FROM wgos.contracting_signers ORDER BY brand_id,position,id`,
  sql`SELECT * FROM wgos.signature_envelopes ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.payments ORDER BY paid_at NULLS LAST,id`,
  sql`SELECT * FROM wgos.refund_events ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.invoices ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.projects ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.tasks ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.task_comments ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.task_dependencies ORDER BY task_id,depends_on_task_id`,
  sql`SELECT * FROM wgos.recurring_task_rules ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.recurring_task_runs ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.calendar_events ORDER BY start_at,id`,
  sql`SELECT * FROM wgos.communication_threads ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.communication_messages ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.equipment_assets ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.crew_profiles ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.project_crew_assignments ORDER BY project_id,crew_profile_id`,
  sql`SELECT * FROM wgos.project_equipment_assignments ORDER BY project_id,equipment_asset_id`,
  sql`SELECT * FROM wgos.production_events ORDER BY event_start NULLS LAST,id`,
  sql`SELECT * FROM wgos.production_departments ORDER BY production_event_id,id`,
  sql`SELECT * FROM wgos.production_requirements ORDER BY production_event_id,id`,
  sql`SELECT * FROM wgos.run_of_show_items ORDER BY production_event_id,position,id`,
  sql`SELECT * FROM wgos.advancing_checkpoints ORDER BY production_event_id,due_at NULLS LAST,id`,
  sql`SELECT * FROM wgos.approval_requests ORDER BY requested_at,id`,
  sql`SELECT * FROM wgos.document_templates ORDER BY brand_id,kind,name,version,id`,
  sql`SELECT * FROM wgos.document_versions ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.automation_rules ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.workflow_definitions ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.workflow_runs ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.outbox_events ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.dead_letter_events ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.notification_events ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.ai_action_executions ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.idempotency_keys ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.provider_events ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.system_health_events ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.custom_field_definitions ORDER BY brand_id,entity_type,name,id`,
  sql`SELECT * FROM wgos.custom_field_values ORDER BY entity_type,entity_id,field_definition_id`,
  sql`SELECT * FROM wgos.tags ORDER BY brand_id,name,id`,
  sql`SELECT * FROM wgos.entity_tags ORDER BY entity_type,entity_id,tag_id`,
  sql`SELECT * FROM wgos.saved_views ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.data_governance_policies ORDER BY brand_id,data_classification,id`,
  sql`SELECT * FROM wgos.data_jobs ORDER BY created_at,id`,
  sql`SELECT * FROM wgos.audit_events ORDER BY created_at,id`,
  sql`SELECT id,brand_id,contact_id,organization_id,status,expires_at,created_at,last_accessed_at FROM wgos.client_portal_access ORDER BY created_at,id`
 ]);

 const data={
  brands,appUsers,brandMemberships,brandGovernance,brandExperienceProfiles,brandDeliveryProfiles,brandPaymentProfiles,
  legalEntityVersions,agreementPartyTransitions,integrations,integrationLinks,externalObjectMappings,
  organizations,organizationBrands,contacts,contactBrands,crossBrandReferrals,
  opportunities,proposals,proposalSections,proposalLineItems,acceptedSnapshots,proposalAccessTokens,
  agreementTerms,agreements,contractingProfiles,contractingSigners,signatureEnvelopes,
  payments,refundEvents,invoices,projects,tasks,taskComments,taskDependencies,recurringTaskRules,recurringTaskRuns,
  calendarEvents,communicationThreads,communicationMessages,equipmentAssets,crewProfiles,projectCrewAssignments,
  projectEquipmentAssignments,productionEvents,productionDepartments,productionRequirements,runOfShowItems,
  advancingCheckpoints,approvalRequests,documentTemplates,documentVersions,automationRules,workflowDefinitions,
  workflowRuns,outboxEvents,deadLetterEvents,notificationEvents,aiActionExecutions,idempotencyKeys,providerEvents,
  systemHealthEvents,customFieldDefinitions,customFieldValues,tags,entityTags,savedViews,dataGovernancePolicies,
  dataJobs,auditEvents,clientPortalAccess
 };
 return {
  format:"WGOS_SYSTEM_EXPORT",
  version:2,
  exportedAt:new Date().toISOString(),
  security:{secretsIncluded:false,accessTokenHashesIncluded:false,authSessionsIncluded:false},
  counts:countMap(data as Record<string,unknown[]>),
  data
 };
}