import AdminNav from "../AdminNav";
import EquipmentWorkspace from "../EquipmentWorkspace";
import {relationshipReferenceData} from "../../../lib/relationships";
import {listEquipmentAssets} from "../../../lib/resources";
import {commandAccess} from "../../../lib/authz";
export default async function EquipmentPage({searchParams}:{searchParams:Promise<{brand?:string;asset?:string}>}){
 const query=await searchParams;const access=await commandAccess();let refs:any={brands:[]},assets:any[]=[];try{[refs,assets]=await Promise.all([relationshipReferenceData(),listEquipmentAssets()]);if(!access.isGlobal){const allowed=new Set(access.brandIds||[]);refs={...refs,brands:refs.brands.filter((x:any)=>allowed.has(x.id))};assets=assets.filter((x:any)=>allowed.has(x.brand_id));}}catch{}
 const selectedBrand=refs.brands.some((b:any)=>b.id===query.brand)?String(query.brand):"";if(selectedBrand)assets=assets.filter((x:any)=>x.brand_id===selectedBrand);
 const available=assets.filter((a:any)=>["AVAILABLE","READY"].includes(String(a.status||"").toUpperCase())).length;const attention=assets.filter((a:any)=>["MAINTENANCE","REPAIR","OUT_OF_SERVICE"].includes(String(a.status||"").toUpperCase())).length;
 return <main className="admin"><AdminNav active="equipment" brands={refs.brands} brand={selectedBrand}/><header className="adminHead commandHero"><div><p className="eyebrow">WGOS · PRODUCTION ASSETS</p><h1>Resource Command</h1><p>Availability, condition and deployment readiness before a commercial promise becomes a production problem.</p><div className="heroSignals"><span>● {available} READY</span><span>◇ {assets.length} ASSETS</span><span>! {attention} ATTENTION</span></div></div></header><section className="workspacePulse"><article><small>ASSETS</small><strong>{assets.length}</strong><span>in current scope</span></article><article><small>AVAILABLE</small><strong>{available}</strong><span>ready to deploy</span></article><article><small>ATTENTION</small><strong>{attention}</strong><span>maintenance or service</span></article></section><section className="principle"><strong>Resource rule:</strong> protect inventory, dates and scope before commitments are made.</section><EquipmentWorkspace assets={assets} brands={refs.brands} initialAssetId={query.asset||""}/></main>;
}
