import AdminNav from "../AdminNav";
import CommunicationWorkspace from "../CommunicationWorkspace";
import {relationshipReferenceData} from "../../../lib/relationships";
import {listCommunicationThreads,listThreadMessages} from "../../../lib/communications";
import {commandAccess} from "../../../lib/authz";
export default async function CommunicationsPage({searchParams}:{searchParams:Promise<{thread?:string;brand?:string}>}){
 const query=await searchParams;const access=await commandAccess();let refs:any={brands:[],organizations:[],contacts:[]},threads:any[]=[],messages:any[]=[];try{[refs,threads]=await Promise.all([relationshipReferenceData(),listCommunicationThreads()]);if(!access.isGlobal){const allowed=new Set(access.brandIds||[]);refs={...refs,brands:refs.brands.filter((x:any)=>allowed.has(x.id)),organizations:refs.organizations.filter((x:any)=>(x.brand_ids||[]).some((id:string)=>allowed.has(id))),contacts:(refs.contacts||[]).filter((x:any)=>(x.brand_ids||[]).some((id:string)=>allowed.has(id)))};threads=threads.filter((x:any)=>allowed.has(x.brand_id));}const selected=threads.some((x:any)=>x.id===query.thread)?query.thread:threads[0]?.id;if(selected)messages=await listThreadMessages(String(selected));}catch{}
 const selectedBrand=refs.brands.some((b:any)=>b.id===query.brand)?String(query.brand):"";if(selectedBrand)threads=threads.filter((x:any)=>x.brand_id===selectedBrand);
 const open=threads.filter((t:any)=>!["CLOSED","ARCHIVED"].includes(String(t.status||"").toUpperCase())).length;const unread=threads.reduce((n:number,t:any)=>n+Number(t.unread_count||0),0);const clientWaiting=threads.filter((t:any)=>t.recent_direction==="INBOUND"&&!["CLOSED","ARCHIVED"].includes(String(t.status||"").toUpperCase()));const waitingOnClient=threads.filter((t:any)=>t.recent_direction==="OUTBOUND"&&!["CLOSED","ARCHIVED"].includes(String(t.status||"").toUpperCase()));
 return <main className="admin"><AdminNav active="communications" brands={refs.brands} brand={selectedBrand}/><header className="adminHead commandHero"><div><p className="eyebrow">WGOS · CLIENT INTELLIGENCE</p><h1>Relationship Command</h1><p>Every promise, conversation and client decision stays connected to the operating record.</p><div className="heroSignals"><span>● {open} OPEN</span><span>◌ {unread} UNREAD</span><span>↗ {threads.length} THREADS</span></div></div></header><section className="workspacePulse"><article><small>THREADS</small><strong>{threads.length}</strong><span>in current scope</span></article><article><small>OPEN</small><strong>{open}</strong><span>active conversations</span></article><article><small>UNREAD</small><strong>{unread}</strong><span>requiring review</span></article></section><section className="adminPanel communicationQueue"><div className="attentionIntro"><p className="eyebrow">RESPONSE AUTOPILOT</p><h2>{clientWaiting.length?clientWaiting.length+" client"+(clientWaiting.length===1?" is":"s are")+" waiting on us":"No client response is waiting"}</h2><p>{clientWaiting.length?"Inbound conversations rise automatically so response obligations do not disappear inside the inbox.":waitingOnClient.length?waitingOnClient.length+" active conversation"+(waitingOnClient.length===1?" is":"s are")+" currently waiting on the client.":"The communication queue is clear."}</p></div><div className="communicationDecisionList">{clientWaiting.slice(0,6).map((t:any)=><a key={t.id} href={"/admin/communications?thread="+encodeURIComponent(t.id)+(selectedBrand?"&brand="+encodeURIComponent(selectedBrand):"")} className="communicationDecisionItem"><span>{t.brand_name||"CLIENT"}</span><strong>{t.subject||t.organization_name||"Client conversation"}</strong><small>{t.recent_at?"Received "+new Date(t.recent_at).toLocaleString():"Inbound response"}</small><b>Respond →</b></a>)}</div></section><section className="principle"><strong>Communication rule:</strong> context follows the relationship. Important commitments become operating records, not lost messages.</section><CommunicationWorkspace threads={threads} messages={messages} brands={refs.brands} organizations={refs.organizations} contacts={refs.contacts||[]} selectedId={query.thread}/></main>;
}
